#PART A — MERGING TABULAR FILES IN GOOGLE COLAB

In [ ]:
# Move to working directory
%cd /content

/content

###Clone the GitHub repository in Colab

In [ ]:
# Clone your GitHub repository
!git clone https://github.com/sandipbarik-bioinfo/Whole-Exome-sequencing-Variant-Analysis.git

Cloning into 'Whole-Exome-sequencing-Variant-Analysis'...
remote: Enumerating objects: 255, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 255 (delta 1), reused 9 (delta 1), pack-reused 243 (from 1)
Receiving objects: 100% (255/255), 188.35 MiB | 17.79 MiB/s, done.
Resolving deltas: 100% (108/108), done.
Updating files: 100% (226/226), done.
Filtering content: 100% (111/111), 3.57 GiB | 53.63 MiB/s, done.

###Define the directory containing all extracted and locate the extracted tabular files

In [ ]:
import glob

# tabular variant files from WES analysis
tabular_dir = "/content/Whole-Exome-sequencing-Variant-Analysis/data/tabular_extracted"

# sorted() ensures consistent ordering across runs
tabular_files = sorted(glob.glob(f"{tabular_dir}/*.tabular"))

# Print the total number of tabular files found
print("Total tabular files found:", len(tabular_files))
tabular_files[:5]

Total tabular files found: 111

['/content/Whole-Exome-sequencing-Variant-Analysis/data/tabular_extracted/SRR8898191.tabular',
 '/content/Whole-Exome-sequencing-Variant-Analysis/data/tabular_extracted/SRR8898192.tabular',
 '/content/Whole-Exome-sequencing-Variant-Analysis/data/tabular_extracted/SRR8898193.tabular',
 '/content/Whole-Exome-sequencing-Variant-Analysis/data/tabular_extracted/SRR8898194.tabular',
 '/content/Whole-Exome-sequencing-Variant-Analysis/data/tabular_extracted/SRR8898195.tabular']

In [ ]:
import pandas as pd

# Load one sample tabular file to inspect the structure

df_test = pd.read_csv(tabular_files[0], sep="\t")
df_test.head()

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,DP,AF,GEN[0].GT,GEN[0].AD,GEN[0].GQ,ANN[*].GENE,ANN[*].EFFECT,ANN[*].IMPACT,ANN[*].HGVS_C,ANN[*].HGVS_P,ANN[*].BIOTYPE,LOF,NMD
0,chr1,69511,.,A,G,8341.980,.,338,1.0,1/1,"0,338",.,OR4F5,missense_variant,MODERATE,c.421A>G,p.Thr141Ala,protein_coding,.,.
1,chr1,942451,.,T,C,429.746,.,15,1.0,1/1,"0,15",.,SAMD11,missense_variant,MODERATE,c.505T>C,p.Trp169Arg,protein_coding,.,.
2,chr1,942451,.,T,C,429.746,.,15,1.0,1/1,"0,15",.,SAMD11,missense_variant,MODERATE,c.1030T>C,p.Trp344Arg,protein_coding,.,.
3,chr1,942451,.,T,C,429.746,.,15,1.0,1/1,"0,15",.,SAMD11,missense_variant,MODERATE,c.1027T>C,p.Trp343Arg,protein_coding,.,.
4,chr1,942451,.,T,C,429.746,.,15,1.0,1/1,"0,15",.,SAMD11,missense_variant,MODERATE,c.703T>C,p.Trp235Arg,protein_coding,.,.

###Merge All tabular files

In [ ]:
merged_df_list = []

#  Loop through each tabular file
# - Extract sample ID from filename
# - Read the tabular file
# - Add Sample_ID column
# - Append to the list

for file in tabular_files:
    sample_id = file.split("/")[-1].replace(".tabular", "")
    df = pd.read_csv(file, sep="\t")
    df["Sample_ID"] = sample_id
    merged_df_list.append(df)

# Merge (concatenate) all sample DataFrames into a single combined DataFrame
merged_df = pd.concat(merged_df_list, ignore_index=True)

print("Merged shape:", merged_df.shape)
merged_df.head()

Merged shape: (15792656, 30)

,CHROM,POS,ID,REF,ALT,QUAL,FILTER,DP,AF,GEN[0].GT,...,Sample_ID,AB,GQ,AO,RO,GT,AD,LOF[*].GENE,NMD[*].GENE,version https://git-lfs.github.com/spec/v1
0,chr1,69511.0,.,A,G,8341.980,.,338.0,1.0,1/1,...,SRR8898191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,chr1,942451.0,.,T,C,429.746,.,15.0,1.0,1/1,...,SRR8898191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chr1,942451.0,.,T,C,429.746,.,15.0,1.0,1/1,...,SRR8898191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,chr1,942451.0,.,T,C,429.746,.,15.0,1.0,1/1,...,SRR8898191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,chr1,942451.0,.,T,C,429.746,.,15.0,1.0,1/1,...,SRR8898191,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Warning: Total number of columns (30) exceeds max_columns (20) limiting to first (20) columns.

###Save merged table

In [ ]:
# Save the merged variant dataas a TSV file for downstream analysis

output_file = "Merged_AD_WES_variants.tsv"
merged_df.to_csv(output_file, sep="\t", index=False)

print("Saved:", output_file)

Saved: Merged_AD_WES_variants.tsv

###Basic sanity checks

In [ ]:
# Number of variants per sample
merged_df["Sample_ID"].value_counts().head()

# Check missing values
merged_df.isnull().sum().sort_values(ascending=False).head(10)

version https://git-lfs.github.com/spec/v1    15792652
GT                                            13556181
RO                                            13556181
AD                                            13556181
AB                                            13556181
AO                                            13556181
GQ                                            13556181
LOF[*].GENE                                   10696244
NMD[*].GENE                                   10696244
LOF                                            5096416
dtype: int64

###Download of Merged_AD_WES_variants.tsv

In [ ]:
from google.colab import files

files.download('/content/Merged_AD_WES_variants.tsv')

In [ ]:
for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):
    print(chunk.head()) # Processes 100,000 rows at a time

  CHROM       POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  ...  \
0  chr1   69511.0  .   A   G  8341.980      .  338.0  1.0       1/1  ...
1  chr1  942451.0  .   T   C   429.746      .   15.0  1.0       1/1  ...
2  chr1  942451.0  .   T   C   429.746      .   15.0  1.0       1/1  ...
3  chr1  942451.0  .   T   C   429.746      .   15.0  1.0       1/1  ...
4  chr1  942451.0  .   T   C   429.746      .   15.0  1.0       1/1  ...

    Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
0  SRR8898191 NaN NaN NaN NaN NaN NaN         NaN         NaN
1  SRR8898191 NaN NaN NaN NaN NaN NaN         NaN         NaN
2  SRR8898191 NaN NaN NaN NaN NaN NaN         NaN         NaN
3  SRR8898191 NaN NaN NaN NaN NaN NaN         NaN         NaN
4  SRR8898191 NaN NaN NaN NaN NaN NaN         NaN         NaN

  version https://git-lfs.github.com/spec/v1
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN

[5 rows x 30 columns]
       CHROM          POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
100000  chr3  138314339.0  .   C   T  12440.40      .  377.0  1.0       1/1
100001  chr3  138314339.0  .   C   T  12440.40      .  377.0  1.0       1/1
100002  chr3  138314339.0  .   C   T  12440.40      .  377.0  1.0       1/1
100003  chr3  138314339.0  .   C   T  12440.40      .  377.0  1.0       1/1
100004  chr3  138372859.0  .   G   T   7872.68      .  248.0  1.0       1/1

        ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
100000  ...  SRR8898191 NaN NaN NaN NaN NaN NaN         NaN         NaN
100001  ...  SRR8898191 NaN NaN NaN NaN NaN NaN         NaN         NaN
100002  ...  SRR8898191 NaN NaN NaN NaN NaN NaN         NaN         NaN
100003  ...  SRR8898191 NaN NaN NaN NaN NaN NaN         NaN         NaN
100004  ...  SRR8898191 NaN NaN NaN NaN NaN NaN         NaN         NaN

       version https://git-lfs.github.com/spec/v1
100000                                        NaN
100001                                        NaN
100002                                        NaN
100003                                        NaN
100004                                        NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
200000  chr17  73196524.0  .   G   A  5889.95      .  170.0  1.0       1/1
200001  chr17  73196734.0  .   A   G  3252.73      .   99.0  1.0       1/1
200002  chr17  73196734.0  .   A   G  3252.73      .   99.0  1.0       1/1
200003  chr17  73196734.0  .   A   G  3252.73      .   99.0  1.0       1/1
200004  chr17  73196734.0  .   A   G  3252.73      .   99.0  1.0       1/1

        ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
200000  ...  SRR8898192 NaN NaN NaN NaN NaN NaN         NaN         NaN
200001  ...  SRR8898192 NaN NaN NaN NaN NaN NaN         NaN         NaN
200002  ...  SRR8898192 NaN NaN NaN NaN NaN NaN         NaN         NaN
200003  ...  SRR8898192 NaN NaN NaN NaN NaN NaN         NaN         NaN
200004  ...  SRR8898192 NaN NaN NaN NaN NaN NaN         NaN         NaN

       version https://git-lfs.github.com/spec/v1
200000                                        NaN
200001                                        NaN
200002                                        NaN
200003                                        NaN
200004                                        NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT  ...  GT  AD  LOF[*].GENE  NMD[*].GENE  \
300000  chr11  44903399.0  .  GC   G  ... NaN NaN          NaN          NaN
300001  chr11  44903399.0  .  GC   G  ... NaN NaN          NaN          NaN
300002  chr11  44903399.0  .  GC   G  ... NaN NaN          NaN          NaN
300003  chr11  44903399.0  .  GC   G  ... NaN NaN          NaN          NaN
300004  chr11  44903399.0  .  GC   G  ... NaN NaN          NaN          NaN

       version https://git-lfs.github.com/spec/v1
300000                                        NaN
300001                                        NaN
300002                                        NaN
300003                                        NaN
300004                                        NaN

[5 rows x 30 columns]
       CHROM          POS ID  REF  ALT          QUAL FILTER     DP   AF  \
400000  chr7  100958468.0  .  AGA  GGT  1.735810e-14      .  280.0  0.0
400001  chr7  100958468.0  .  AGA  GGT  1.735810e-14      .  280.0  0.0
400002  chr7  100958470.0  .    A    T  1.735810e-14      .  280.0  0.0
400003  chr7  100958470.0  .    A    T  1.735810e-14      .  280.0  0.0
400004  chr7  100958470.0  .    A    T  1.735810e-14      .  280.0  0.0

       GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
400000       0/0  ...  SRR8898193 NaN NaN NaN NaN NaN NaN         NaN
400001       0/0  ...  SRR8898193 NaN NaN NaN NaN NaN NaN         NaN
400002       0/0  ...  SRR8898193 NaN NaN NaN NaN NaN NaN         NaN
400003       0/0  ...  SRR8898193 NaN NaN NaN NaN NaN NaN         NaN
400004       0/0  ...  SRR8898193 NaN NaN NaN NaN NaN NaN         NaN

       NMD[*].GENE version https://git-lfs.github.com/spec/v1
400000         NaN                                        NaN
400001         NaN                                        NaN
400002         NaN                                        NaN
400003         NaN                                        NaN
400004         NaN                                        NaN

[5 rows x 30 columns]
       CHROM          POS ID REF ALT          QUAL FILTER     DP   AF  \
500000  chr2  131264335.0  .   G   A  4.889500e-11      .   76.0  0.5
500001  chr2  131264373.0  .   G   A  1.621740e-04      .   38.0  0.5
500002  chr2  131264373.0  .   G   A  1.621740e-04      .   38.0  0.5
500003  chr2  131363508.0  .   A   C  0.000000e+00      .  146.0  0.0
500004  chr2  131363508.0  .   A   C  0.000000e+00      .  146.0  0.0

       GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
500000       0/1  ...  SRR8898194 NaN NaN NaN NaN NaN NaN         NaN
500001       0/1  ...  SRR8898194 NaN NaN NaN NaN NaN NaN         NaN
500002       0/1  ...  SRR8898194 NaN NaN NaN NaN NaN NaN         NaN
500003       0/0  ...  SRR8898194 NaN NaN NaN NaN NaN NaN         NaN
500004       0/0  ...  SRR8898194 NaN NaN NaN NaN NaN NaN         NaN

       NMD[*].GENE version https://git-lfs.github.com/spec/v1
500000         NaN                                        NaN
500001         NaN                                        NaN
500002         NaN                                        NaN
500003         NaN                                        NaN
500004         NaN                                        NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
600000  chr14  24440269.0  .   C   G  6303.34      .  487.0  0.5       0/1
600001  chr14  24440269.0  .   C   G  6303.34      .  487.0  0.5       0/1
600002  chr14  24440525.0  .   C   T  6800.82      .  530.0  0.5       0/1
600003  chr14  24440525.0  .   C   T  6800.82      .  530.0  0.5       0/1
600004  chr14  24440525.0  .   C   T  6800.82      .  530.0  0.5       0/1

        ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
600000  ...  SRR8898195 NaN NaN NaN NaN NaN NaN         NaN         NaN
600001  ...  SRR8898195 NaN NaN NaN NaN NaN NaN         NaN         NaN
600002  ...  SRR8898195 NaN NaN NaN NaN NaN NaN         NaN         NaN
600003  ...  SRR8898195 NaN NaN NaN NaN NaN NaN         NaN         NaN
600004  ...  SRR8898195 NaN NaN NaN NaN NaN NaN         NaN         NaN

       version https://git-lfs.github.com/spec/v1
600000                                        NaN
600001                                        NaN
600002                                        NaN
600003                                        NaN
600004                                        NaN

[5 rows x 30 columns]
       CHROM         POS ID            REF ALT      QUAL FILTER    DP   AF  \
700000  chrX  38285927.0  .  CTCCCCTTCCACT   C  0.251759      .  14.0  0.5
700001  chrX  38285927.0  .  CTCCCCTTCCACT   C  0.251759      .  14.0  0.5
700002  chrX  38285927.0  .  CTCCCCTTCCACT   C  0.251759      .  14.0  0.5
700003  chrX  38285927.0  .  CTCCCCTTCCACT   C  0.251759      .  14.0  0.5
700004  chrX  38285927.0  .  CTCCCCTTCCACT   C  0.251759      .  14.0  0.5

       GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
700000       0/1  ...  SRR8898195 NaN NaN NaN NaN NaN NaN         NaN
700001       0/1  ...  SRR8898195 NaN NaN NaN NaN NaN NaN         NaN
700002       0/1  ...  SRR8898195 NaN NaN NaN NaN NaN NaN         NaN
700003       0/1  ...  SRR8898195 NaN NaN NaN NaN NaN NaN         NaN
700004       0/1  ...  SRR8898195 NaN NaN NaN NaN NaN NaN         NaN

       NMD[*].GENE version https://git-lfs.github.com/spec/v1
700000         NaN                                        NaN
700001         NaN                                        NaN
700002         NaN                                        NaN
700003         NaN                                        NaN
700004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,22,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

       CHROM         POS ID REF   ALT     QUAL FILTER     DP   AF GEN[0].GT  \
800000  chr3  52550415.0  .   T  TCTC  1471.90      .  125.0  0.5       0/1
800001  chr3  52550415.0  .   T  TCTC  1471.90      .  125.0  0.5       0/1
800002  chr3  52550415.0  .   T  TCTC  1471.90      .  125.0  0.5       0/1
800003  chr3  52550415.0  .   T  TCTC  1471.90      .  125.0  0.5       0/1
800004  chr3  52550771.0  .   T     C  1457.51      .  142.0  0.5       0/1

        ...   Sample_ID  AB   GQ  AO  RO   GT   AD LOF[*].GENE NMD[*].GENE  \
800000  ...  SRR8898196 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
800001  ...  SRR8898196 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
800002  ...  SRR8898196 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
800003  ...  SRR8898196 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
800004  ...  SRR8898196 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN

       version https://git-lfs.github.com/spec/v1
800000                                        NaN
800001                                        NaN
800002                                        NaN
800003                                        NaN
800004                                        NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT     QUAL FILTER    DP   AF  GEN[0].GT  \
900000  chr17  40019175.0  .   A   C  104.491      .  55.0  0.5        NaN
900001  chr17  40019175.0  .   A   C  104.491      .  55.0  0.5        NaN
900002  chr17  40019175.0  .   A   C  104.491      .  55.0  0.5        NaN
900003  chr17  40019175.0  .   A   C  104.491      .  55.0  0.5        NaN
900004  chr17  40019175.0  .   A   C  104.491      .  55.0  0.5        NaN

        ...   Sample_ID        AB GQ   AO    RO  GT AD LOF[*].GENE  \
900000  ...  SRR8898197  0.163636  .  9.0  27.0   .  .         NaN
900001  ...  SRR8898197  0.163636  .  9.0  27.0   .  .         NaN
900002  ...  SRR8898197  0.163636  .  9.0  27.0   .  .         NaN
900003  ...  SRR8898197  0.163636  .  9.0  27.0   .  .         NaN
900004  ...  SRR8898197  0.163636  .  9.0  27.0   .  .         NaN

       NMD[*].GENE version https://git-lfs.github.com/spec/v1
900000         NaN                                        NaN
900001         NaN                                        NaN
900002         NaN                                        NaN
900003         NaN                                        NaN
900004         NaN                                        NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT     QUAL FILTER     DP   AF  GEN[0].GT  \
1000000  chr10  120457350.0  .   C   T  5270.65      .  493.0  0.5        NaN
1000001  chr10  120860227.0  .   T   C  4092.32      .  412.0  0.5        NaN
1000002  chr10  120860227.0  .   T   C  4092.32      .  412.0  0.5        NaN
1000003  chr10  120860227.0  .   T   C  4092.32      .  412.0  0.5        NaN
1000004  chr10  120860227.0  .   T   C  4092.32      .  412.0  0.5        NaN

         ...   Sample_ID        AB GQ     AO     RO  GT AD LOF[*].GENE  \
1000000  ...  SRR8898198  0.423935  .  209.0  284.0   .  .         NaN
1000001  ...  SRR8898198  0.410194  .  169.0  243.0   .  .         NaN
1000002  ...  SRR8898198  0.410194  .  169.0  243.0   .  .         NaN
1000003  ...  SRR8898198  0.410194  .  169.0  243.0   .  .         NaN
1000004  ...  SRR8898198  0.410194  .  169.0  243.0   .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
1000000         NaN                                        NaN
1000001         NaN                                        NaN
1000002         NaN                                        NaN
1000003         NaN                                        NaN
1000004         NaN                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID   REF ALT     QUAL FILTER     DP   AF  \
1100000  chr6  159790604.0  .     G   A  14010.6      .  434.0  1.0
1100001  chr6  159790604.0  .     G   A  14010.6      .  434.0  1.0
1100002  chr6  159790604.0  .     G   A  14010.6      .  434.0  1.0
1100003  chr6  159790604.0  .     G   A  14010.6      .  434.0  1.0
1100004  chr6  159790613.0  .  GGTT   G  10849.8      .  374.0  1.0

         GEN[0].GT  ...   Sample_ID   AB GQ     AO   RO  GT AD LOF[*].GENE  \
1100000        NaN  ...  SRR8898198  0.0  .  434.0  0.0   .  .         NaN
1100001        NaN  ...  SRR8898198  0.0  .  434.0  0.0   .  .         NaN
1100002        NaN  ...  SRR8898198  0.0  .  434.0  0.0   .  .         NaN
1100003        NaN  ...  SRR8898198  0.0  .  434.0  0.0   .  .         NaN
1100004        NaN  ...  SRR8898198  0.0  .  373.0  0.0   .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
1100000         NaN                                        NaN
1100001         NaN                                        NaN
1100002         NaN                                        NaN
1100003         NaN                                        NaN
1100004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,22,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

        CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
1200000  chr2  96328146.0  .   A   G  3981.02      .  291.0  0.5       NaN
1200001  chr2  96328146.0  .   A   G  3981.02      .  291.0  0.5       NaN
1200002  chr2  96328146.0  .   A   G  3981.02      .  291.0  0.5       NaN
1200003  chr2  96328146.0  .   A   G  3981.02      .  291.0  0.5       NaN
1200004  chr2  96354311.0  .   T   C  4051.39      .  341.0  0.5       NaN

         ...   Sample_ID        AB GQ     AO     RO GT AD LOF[*].GENE  \
1200000  ...  SRR8898199  0.515464  .  150.0  141.0  .  .         NaN
1200001  ...  SRR8898199  0.515464  .  150.0  141.0  .  .         NaN
1200002  ...  SRR8898199  0.515464  .  150.0  141.0  .  .         NaN
1200003  ...  SRR8898199  0.515464  .  150.0  141.0  .  .         NaN
1200004  ...  SRR8898199  0.457478  .  156.0  185.0  .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
1200000         NaN                                        NaN
1200001         NaN                                        NaN
1200002         NaN                                        NaN
1200003         NaN                                        NaN
1200004         NaN                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
1300000  chr14  74299649.0  .   A   G  1512.15      .  116.0  0.5       0/1
1300001  chr14  74299649.0  .   A   G  1512.15      .  116.0  0.5       0/1
1300002  chr14  74299649.0  .   A   G  1512.15      .  116.0  0.5       0/1
1300003  chr14  74299649.0  .   A   G  1512.15      .  116.0  0.5       0/1
1300004  chr14  74299649.0  .   A   G  1512.15      .  116.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
1300000  ...  SRR8898200 NaN NaN NaN NaN NaN NaN         NaN         NaN
1300001  ...  SRR8898200 NaN NaN NaN NaN NaN NaN         NaN         NaN
1300002  ...  SRR8898200 NaN NaN NaN NaN NaN NaN         NaN         NaN
1300003  ...  SRR8898200 NaN NaN NaN NaN NaN NaN         NaN         NaN
1300004  ...  SRR8898200 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
1300000                                        NaN
1300001                                        NaN
1300002                                        NaN
1300003                                        NaN
1300004                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT         QUAL FILTER     DP   AF  \
1400000  chrX  154413367.0  .  TG   T     0.000039      .   19.0  0.5
1400001  chrX  154428737.0  .   G   A  2995.440000      .  254.0  0.5
1400002  chrX  154428737.0  .   G   A  2995.440000      .  254.0  0.5
1400003  chrX  154428737.0  .   G   A  2995.440000      .  254.0  0.5
1400004  chrX  154428737.0  .   G   A  2995.440000      .  254.0  0.5

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
1400000       0/1  ...  SRR8898200 NaN NaN NaN NaN NaN NaN         NaN
1400001       0/1  ...  SRR8898200 NaN NaN NaN NaN NaN NaN         NaN
1400002       0/1  ...  SRR8898200 NaN NaN NaN NaN NaN NaN         NaN
1400003       0/1  ...  SRR8898200 NaN NaN NaN NaN NaN NaN         NaN
1400004       0/1  ...  SRR8898200 NaN NaN NaN NaN NaN NaN         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
1400000         NaN                                        NaN
1400001         NaN                                        NaN
1400002         NaN                                        NaN
1400003         NaN                                        NaN
1400004         NaN                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
1500000  chr3  150667020.0  .   T   G  8057.20      .  253.0  1.0     1-Jan
1500001  chr3  150667020.0  .   T   G  8057.20      .  253.0  1.0     1-Jan
1500002  chr3  150674023.0  .   A   C  9264.81      .  642.0  0.5       0/1
1500003  chr3  150674023.0  .   A   C  9264.81      .  642.0  0.5       0/1
1500004  chr3  150674023.0  .   A   C  9264.81      .  642.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
1500000  ...  SRR8898201 NaN NaN NaN NaN NaN NaN         NaN         NaN
1500001  ...  SRR8898201 NaN NaN NaN NaN NaN NaN         NaN         NaN
1500002  ...  SRR8898201 NaN NaN NaN NaN NaN NaN         NaN         NaN
1500003  ...  SRR8898201 NaN NaN NaN NaN NaN NaN         NaN         NaN
1500004  ...  SRR8898201 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
1500000                                        NaN
1500001                                        NaN
1500002                                        NaN
1500003                                        NaN
1500004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
1600000  chr17  50354963.0  .   G   C   9216.01      .  279.0  1.0       1/1
1600001  chr17  50356597.0  .   T   C  19521.90      .  591.0  1.0       1/1
1600002  chr17  50356597.0  .   T   C  19521.90      .  591.0  1.0       1/1
1600003  chr17  50356597.0  .   T   C  19521.90      .  591.0  1.0       1/1
1600004  chr17  50356597.0  .   T   C  19521.90      .  591.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
1600000  ...  SRR8898202 NaN NaN NaN NaN NaN NaN         NaN         NaN
1600001  ...  SRR8898202 NaN NaN NaN NaN NaN NaN         NaN         NaN
1600002  ...  SRR8898202 NaN NaN NaN NaN NaN NaN         NaN         NaN
1600003  ...  SRR8898202 NaN NaN NaN NaN NaN NaN         NaN         NaN
1600004  ...  SRR8898202 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
1600000                                        NaN
1600001                                        NaN
1600002                                        NaN
1600003                                        NaN
1600004                                        NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
1700000  chr10  100984574.0  .   A   T  3738.41      .  352.0  0.5       0/1
1700001  chr10  100984574.0  .   A   T  3738.41      .  352.0  0.5       0/1
1700002  chr10  100984574.0  .   A   T  3738.41      .  352.0  0.5       0/1
1700003  chr10  100984574.0  .   A   T  3738.41      .  352.0  0.5       0/1
1700004  chr10  100984574.0  .   A   T  3738.41      .  352.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
1700000  ...  SRR8898203 NaN NaN NaN NaN NaN NaN           .            .
1700001  ...  SRR8898203 NaN NaN NaN NaN NaN NaN           .            .
1700002  ...  SRR8898203 NaN NaN NaN NaN NaN NaN           .            .
1700003  ...  SRR8898203 NaN NaN NaN NaN NaN NaN           .            .
1700004  ...  SRR8898203 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
1700000                                         NaN
1700001                                         NaN
1700002                                         NaN
1700003                                         NaN
1700004                                         NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
1800000  chr5  14498618.0  .   G   A  9996.86      .  740.0  0.5       0/1
1800001  chr5  14498618.0  .   G   A  9996.86      .  740.0  0.5       0/1
1800002  chr5  14498618.0  .   G   A  9996.86      .  740.0  0.5       0/1
1800003  chr5  14498618.0  .   G   A  9996.86      .  740.0  0.5       0/1
1800004  chr5  14498618.0  .   G   A  9996.86      .  740.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
1800000  ...  SRR8898203 NaN NaN NaN NaN NaN NaN           .            .
1800001  ...  SRR8898203 NaN NaN NaN NaN NaN NaN           .            .
1800002  ...  SRR8898203 NaN NaN NaN NaN NaN NaN           .            .
1800003  ...  SRR8898203 NaN NaN NaN NaN NaN NaN           .            .
1800004  ...  SRR8898203 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
1800000                                         NaN
1800001                                         NaN
1800002                                         NaN
1800003                                         NaN
1800004                                         NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
1900000  chr17  75493486.0  .   C   G  19531.9      .  593.0  1.0       1/1
1900001  chr17  75493486.0  .   C   G  19531.9      .  593.0  1.0       1/1
1900002  chr17  75493486.0  .   C   G  19531.9      .  593.0  1.0       1/1
1900003  chr17  75497793.0  .   G   C   2290.8      .  185.0  0.5       0/1
1900004  chr17  75497793.0  .   G   C   2290.8      .  185.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
1900000  ...  SRR8898204 NaN NaN NaN NaN NaN NaN           .            .
1900001  ...  SRR8898204 NaN NaN NaN NaN NaN NaN           .            .
1900002  ...  SRR8898204 NaN NaN NaN NaN NaN NaN           .            .
1900003  ...  SRR8898204 NaN NaN NaN NaN NaN NaN           .            .
1900004  ...  SRR8898204 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
1900000                                         NaN
1900001                                         NaN
1900002                                         NaN
1900003                                         NaN
1900004                                         NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
2000000  chr10  49131709.0  .   G   T  6712.33      .  556.0  0.5       0/1
2000001  chr10  49131709.0  .   G   T  6712.33      .  556.0  0.5       0/1
2000002  chr10  49131709.0  .   G   T  6712.33      .  556.0  0.5       0/1
2000003  chr10  49131917.0  .   A   T  3050.31      .  221.0  0.5       0/1
2000004  chr10  49131917.0  .   A   T  3050.31      .  221.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
2000000  ...  SRR8898205 NaN NaN NaN NaN NaN NaN           .            .
2000001  ...  SRR8898205 NaN NaN NaN NaN NaN NaN           .            .
2000002  ...  SRR8898205 NaN NaN NaN NaN NaN NaN           .            .
2000003  ...  SRR8898205 NaN NaN NaN NaN NaN NaN           .            .
2000004  ...  SRR8898205 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
2000000                                         NaN
2000001                                         NaN
2000002                                         NaN
2000003                                         NaN
2000004                                         NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
2100000  chr5  139478334.0  .   T   C  8598.08      .  263.0  1.0       1/1
2100001  chr5  139478334.0  .   T   C  8598.08      .  263.0  1.0       1/1
2100002  chr5  139478334.0  .   T   C  8598.08      .  263.0  1.0       1/1
2100003  chr5  139478334.0  .   T   C  8598.08      .  263.0  1.0       1/1
2100004  chr5  139478334.0  .   T   C  8598.08      .  263.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
2100000  ...  SRR8898205 NaN NaN NaN NaN NaN NaN           .            .
2100001  ...  SRR8898205 NaN NaN NaN NaN NaN NaN           .            .
2100002  ...  SRR8898205 NaN NaN NaN NaN NaN NaN           .            .
2100003  ...  SRR8898205 NaN NaN NaN NaN NaN NaN           .            .
2100004  ...  SRR8898205 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
2100000                                         NaN
2100001                                         NaN
2100002                                         NaN
2100003                                         NaN
2100004                                         NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM        POS ID REF ALT       QUAL FILTER     DP   AF GEN[0].GT  \
2200000  chr19  1512964.0  .   G   A    95.4194      .    5.0  0.5       0/1
2200001  chr19  1512964.0  .   G   A    95.4194      .    5.0  0.5       0/1
2200002  chr19  1512964.0  .   G   A    95.4194      .    5.0  0.5       0/1
2200003  chr19  1512964.0  .   G   A    95.4194      .    5.0  0.5       0/1
2200004  chr19  1611857.0  .   G   A  2409.3900      .  256.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
2200000  ...  SRR8898206 NaN NaN NaN NaN NaN NaN           .           .
2200001  ...  SRR8898206 NaN NaN NaN NaN NaN NaN           .           .
2200002  ...  SRR8898206 NaN NaN NaN NaN NaN NaN           .           .
2200003  ...  SRR8898206 NaN NaN NaN NaN NaN NaN           .           .
2200004  ...  SRR8898206 NaN NaN NaN NaN NaN NaN           .           .

        version https://git-lfs.github.com/spec/v1
2200000                                        NaN
2200001                                        NaN
2200002                                        NaN
2200003                                        NaN
2200004                                        NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT          QUAL FILTER    DP   AF  \
2300000  chr10  116911813.0  .   C   A  7.116200e-08      .  25.0  0.0
2300001  chr10  116911813.0  .   C   A  7.116200e-08      .  25.0  0.0
2300002  chr10  116911813.0  .   C   A  7.116200e-08      .  25.0  0.0
2300003  chr10  116911813.0  .   C   A  7.116200e-08      .  25.0  0.0
2300004  chr10  116911813.0  .   C   A  7.116200e-08      .  25.0  0.0

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
2300000       0/0  ...  SRR8898207 NaN NaN NaN NaN NaN NaN         NaN
2300001       0/0  ...  SRR8898207 NaN NaN NaN NaN NaN NaN         NaN
2300002       0/0  ...  SRR8898207 NaN NaN NaN NaN NaN NaN         NaN
2300003       0/0  ...  SRR8898207 NaN NaN NaN NaN NaN NaN         NaN
2300004       0/0  ...  SRR8898207 NaN NaN NaN NaN NaN NaN         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
2300000         NaN                                        NaN
2300001         NaN                                        NaN
2300002         NaN                                        NaN
2300003         NaN                                        NaN
2300004         NaN                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT          QUAL FILTER     DP   AF  \
2400000  chr3  157364354.0  .   T   A  5.478050e-07      .   24.0  0.0
2400001  chr3  157364354.0  .   T   A  5.478050e-07      .   24.0  0.0
2400002  chr3  157364354.0  .   T   A  5.478050e-07      .   24.0  0.0
2400003  chr3  157437525.0  .   C   A  1.372430e+04      .  416.0  1.0
2400004  chr3  157437525.0  .   C   A  1.372430e+04      .  416.0  1.0

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
2400000       0/0  ...  SRR8898207 NaN NaN NaN NaN NaN NaN         NaN
2400001       0/0  ...  SRR8898207 NaN NaN NaN NaN NaN NaN         NaN
2400002       0/0  ...  SRR8898207 NaN NaN NaN NaN NaN NaN         NaN
2400003       1/1  ...  SRR8898207 NaN NaN NaN NaN NaN NaN         NaN
2400004       1/1  ...  SRR8898207 NaN NaN NaN NaN NaN NaN         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
2400000         NaN                                        NaN
2400001         NaN                                        NaN
2400002         NaN                                        NaN
2400003         NaN                                        NaN
2400004         NaN                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
2500000  chr16  69954569.0  .   C   T  290.341      .  124.0  0.5       0/1
2500001  chr16  69954569.0  .   C   T  290.341      .  124.0  0.5       0/1
2500002  chr16  69954569.0  .   C   T  290.341      .  124.0  0.5       0/1
2500003  chr16  69954569.0  .   C   T  290.341      .  124.0  0.5       0/1
2500004  chr16  69954569.0  .   C   T  290.341      .  124.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
2500000  ...  SRR8898208 NaN NaN NaN NaN NaN NaN         NaN         NaN
2500001  ...  SRR8898208 NaN NaN NaN NaN NaN NaN         NaN         NaN
2500002  ...  SRR8898208 NaN NaN NaN NaN NaN NaN         NaN         NaN
2500003  ...  SRR8898208 NaN NaN NaN NaN NaN NaN         NaN         NaN
2500004  ...  SRR8898208 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
2500000                                        NaN
2500001                                        NaN
2500002                                        NaN
2500003                                        NaN
2500004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
2600000  chr10  35175850.0  .   C   T  4841.07      .  397.0  0.5       0/1
2600001  chr10  35175850.0  .   C   T  4841.07      .  397.0  0.5       0/1
2600002  chr10  35175850.0  .   C   T  4841.07      .  397.0  0.5       0/1
2600003  chr10  35175850.0  .   C   T  4841.07      .  397.0  0.5       0/1
2600004  chr10  35175850.0  .   C   T  4841.07      .  397.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
2600000  ...  SRR8898209 NaN NaN NaN NaN NaN NaN         NaN         NaN
2600001  ...  SRR8898209 NaN NaN NaN NaN NaN NaN         NaN         NaN
2600002  ...  SRR8898209 NaN NaN NaN NaN NaN NaN         NaN         NaN
2600003  ...  SRR8898209 NaN NaN NaN NaN NaN NaN         NaN         NaN
2600004  ...  SRR8898209 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
2600000                                        NaN
2600001                                        NaN
2600002                                        NaN
2600003                                        NaN
2600004                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID  REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
2700000  chr5  178931219.0  .  ATT   A  6498.47      .  235.0  1.0       1/1
2700001  chr5  178931219.0  .  ATT   A  6498.47      .  235.0  1.0       1/1
2700002  chr5  178932135.0  .    A   G  7622.42      .  227.0  1.0       1/1
2700003  chr5  178932135.0  .    A   G  7622.42      .  227.0  1.0       1/1
2700004  chr5  178932135.0  .    A   G  7622.42      .  227.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
2700000  ...  SRR8898209 NaN NaN NaN NaN NaN NaN         NaN         NaN
2700001  ...  SRR8898209 NaN NaN NaN NaN NaN NaN         NaN         NaN
2700002  ...  SRR8898209 NaN NaN NaN NaN NaN NaN         NaN         NaN
2700003  ...  SRR8898209 NaN NaN NaN NaN NaN NaN         NaN         NaN
2700004  ...  SRR8898209 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
2700000                                        NaN
2700001                                        NaN
2700002                                        NaN
2700003                                        NaN
2700004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
2800000  chr19  45641767.0  .   G   T  2006.44      .  152.0  0.5       0/1
2800001  chr19  45641767.0  .   G   T  2006.44      .  152.0  0.5       0/1
2800002  chr19  45641767.0  .   G   T  2006.44      .  152.0  0.5       0/1
2800003  chr19  45641767.0  .   G   T  2006.44      .  152.0  0.5       0/1
2800004  chr19  45641767.0  .   G   T  2006.44      .  152.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
2800000  ...  SRR8898210 NaN NaN NaN NaN NaN NaN         NaN         NaN
2800001  ...  SRR8898210 NaN NaN NaN NaN NaN NaN         NaN         NaN
2800002  ...  SRR8898210 NaN NaN NaN NaN NaN NaN         NaN         NaN
2800003  ...  SRR8898210 NaN NaN NaN NaN NaN NaN         NaN         NaN
2800004  ...  SRR8898210 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
2800000                                        NaN
2800001                                        NaN
2800002                                        NaN
2800003                                        NaN
2800004                                        NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT       QUAL FILTER     DP   AF  \
2900000  chr12  110048467.0  .   T   C  1493.4100      .  129.0  0.5
2900001  chr12  110048467.0  .   T   C  1493.4100      .  129.0  0.5
2900002  chr12  110048467.0  .   T   C  1493.4100      .  129.0  0.5
2900003  chr12  110048467.0  .   T   C  1493.4100      .  129.0  0.5
2900004  chr12  110124692.0  .   C   T    20.0471      .    5.0  0.5

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
2900000       0/1  ...  SRR8898211 NaN NaN NaN NaN NaN NaN           .
2900001       0/1  ...  SRR8898211 NaN NaN NaN NaN NaN NaN           .
2900002       0/1  ...  SRR8898211 NaN NaN NaN NaN NaN NaN           .
2900003       0/1  ...  SRR8898211 NaN NaN NaN NaN NaN NaN           .
2900004       0/1  ...  SRR8898211 NaN NaN NaN NaN NaN NaN           .

         NMD[*].GENE  version https://git-lfs.github.com/spec/v1
2900000            .                                         NaN
2900001            .                                         NaN
2900002            .                                         NaN
2900003            .                                         NaN
2900004            .                                         NaN

[5 rows x 30 columns]
        CHROM          POS ID   REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
3000000  chr7  158856613.0  .     T   C  1356.65      .  102.0  0.5       0/1
3000001  chr7  158869491.0  .     G   A  4747.11      .  336.0  0.5       0/1
3000002  chr7  158869491.0  .     G   A  4747.11      .  336.0  0.5       0/1
3000003  chr7  158871383.0  .  TGAA   T  1464.96      .  161.0  0.5       0/1
3000004  chr7  158871383.0  .  TGAA   T  1464.96      .  161.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
3000000  ...  SRR8898211 NaN NaN NaN NaN NaN NaN           .            .
3000001  ...  SRR8898211 NaN NaN NaN NaN NaN NaN       WDR60            .
3000002  ...  SRR8898211 NaN NaN NaN NaN NaN NaN       WDR60            .
3000003  ...  SRR8898211 NaN NaN NaN NaN NaN NaN           .            .
3000004  ...  SRR8898211 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
3000000                                         NaN
3000001                                         NaN
3000002                                         NaN
3000003                                         NaN
3000004                                         NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT  ...  GT  AD  LOF[*].GENE  NMD[*].GENE  \
3100000  chr2  185833149.0  .   A   G  ... NaN NaN            .            .
3100001  chr2  185833149.0  .   A   G  ... NaN NaN            .            .
3100002  chr2  185833149.0  .   A   G  ... NaN NaN            .            .
3100003  chr2  185833149.0  .   A   G  ... NaN NaN            .            .
3100004  chr2  186504215.0  .   G   T  ... NaN NaN       ZC3H15            .

        version https://git-lfs.github.com/spec/v1
3100000                                        NaN
3100001                                        NaN
3100002                                        NaN
3100003                                        NaN
3100004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID  REF ALT          QUAL FILTER     DP   AF  \
3200000  chr14  23389062.0  .  AGG   A  1.080170e+03      .   91.0  0.5
3200001  chr14  23418205.0  .    C   A  9.740690e-13      .   32.0  0.0
3200002  chr14  23475296.0  .    G   A  6.561510e+03      .  591.0  0.5
3200003  chr14  23475296.0  .    G   A  6.561510e+03      .  591.0  0.5
3200004  chr14  23475296.0  .    G   A  6.561510e+03      .  591.0  0.5

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
3200000       0/1  ...  SRR8898213 NaN NaN NaN NaN NaN NaN           .
3200001       0/0  ...  SRR8898213 NaN NaN NaN NaN NaN NaN           .
3200002       0/1  ...  SRR8898213 NaN NaN NaN NaN NaN NaN           .
3200003       0/1  ...  SRR8898213 NaN NaN NaN NaN NaN NaN           .
3200004       0/1  ...  SRR8898213 NaN NaN NaN NaN NaN NaN           .

         NMD[*].GENE  version https://git-lfs.github.com/spec/v1
3200000            .                                         NaN
3200001            .                                         NaN
3200002            .                                         NaN
3200003            .                                         NaN
3200004            .                                         NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

        CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
3300000  chr8  144397883.0  .   C   T  9969.21      .  328.0  1.0       1/1
3300001  chr8  144414297.0  .   C   G  7123.43      .  217.0  1.0       1/1
3300002  chr8  144414297.0  .   C   G  7123.43      .  217.0  1.0       1/1
3300003  chr8  144414342.0  .   T   C  7516.55      .  231.0  1.0       1/1
3300004  chr8  144414342.0  .   T   C  7516.55      .  231.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
3300000  ...  SRR8898213 NaN NaN NaN NaN NaN NaN           .           .
3300001  ...  SRR8898213 NaN NaN NaN NaN NaN NaN           .           .
3300002  ...  SRR8898213 NaN NaN NaN NaN NaN NaN           .           .
3300003  ...  SRR8898213 NaN NaN NaN NaN NaN NaN           .           .
3300004  ...  SRR8898213 NaN NaN NaN NaN NaN NaN           .           .

        version https://git-lfs.github.com/spec/v1
3300000                                        NaN
3300001                                        NaN
3300002                                        NaN
3300003                                        NaN
3300004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
3400000  chr21  33553383.0  .   G   A   7992.3      .  586.0  0.5       0/1
3400001  chr21  33553383.0  .   G   A   7992.3      .  586.0  0.5       0/1
3400002  chr21  33553383.0  .   G   A   7992.3      .  586.0  0.5       0/1
3400003  chr21  33553383.0  .   G   A   7992.3      .  586.0  0.5       0/1
3400004  chr21  33553954.0  .   C   T  24010.8      .  711.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
3400000  ...  SRR8898214 NaN NaN NaN NaN NaN NaN         NaN         NaN
3400001  ...  SRR8898214 NaN NaN NaN NaN NaN NaN         NaN         NaN
3400002  ...  SRR8898214 NaN NaN NaN NaN NaN NaN         NaN         NaN
3400003  ...  SRR8898214 NaN NaN NaN NaN NaN NaN         NaN         NaN
3400004  ...  SRR8898214 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
3400000                                        NaN
3400001                                        NaN
3400002                                        NaN
3400003                                        NaN
3400004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
3500000  chr16  22815018.0  .   A   G  1651.360      .  177.0  0.5       0/1
3500001  chr16  22815018.0  .   A   G  1651.360      .  177.0  0.5       0/1
3500002  chr16  22914936.0  .   C   T   673.805      .   57.0  0.5       0/1
3500003  chr16  22914936.0  .   C   T   673.805      .   57.0  0.5       0/1
3500004  chr16  23069313.0  .   C   A  3519.550      .  277.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
3500000  ...  SRR8898215 NaN NaN NaN NaN NaN NaN         NaN         NaN
3500001  ...  SRR8898215 NaN NaN NaN NaN NaN NaN         NaN         NaN
3500002  ...  SRR8898215 NaN NaN NaN NaN NaN NaN         NaN         NaN
3500003  ...  SRR8898215 NaN NaN NaN NaN NaN NaN         NaN         NaN
3500004  ...  SRR8898215 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
3500000                                        NaN
3500001                                        NaN
3500002                                        NaN
3500003                                        NaN
3500004                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT          QUAL FILTER    DP   AF  \
3600000  chr1  109657274.0  .   C   T  2.206700e-14      .  40.0  0.0
3600001  chr1  109657274.0  .   C   T  2.206700e-14      .  40.0  0.0
3600002  chr1  109657274.0  .   C   T  2.206700e-14      .  40.0  0.0
3600003  chr1  109657274.0  .   C   T  2.206700e-14      .  40.0  0.0
3600004  chr1  109657274.0  .   C   T  2.206700e-14      .  40.0  0.0

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
3600000       0/0  ...  SRR8898216 NaN NaN NaN NaN NaN NaN         NaN
3600001       0/0  ...  SRR8898216 NaN NaN NaN NaN NaN NaN         NaN
3600002       0/0  ...  SRR8898216 NaN NaN NaN NaN NaN NaN         NaN
3600003       0/0  ...  SRR8898216 NaN NaN NaN NaN NaN NaN         NaN
3600004       0/0  ...  SRR8898216 NaN NaN NaN NaN NaN NaN         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
3600000         NaN                                        NaN
3600001         NaN                                        NaN
3600002         NaN                                        NaN
3600003         NaN                                        NaN
3600004         NaN                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT          QUAL FILTER     DP   AF  \
3700000  chr4  169107158.0  .   T   G  1.679920e-11      .   30.0  0.0
3700001  chr4  169107209.0  .  GA   G  5.476560e-01      .   11.0  0.5
3700002  chr4  169156638.0  .   A   G  1.413870e+03      .  133.0  0.5
3700003  chr4  169156638.0  .   A   G  1.413870e+03      .  133.0  0.5
3700004  chr4  169156638.0  .   A   G  1.413870e+03      .  133.0  0.5

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
3700000       0/0  ...  SRR8898216 NaN NaN NaN NaN NaN NaN         NaN
3700001       0/1  ...  SRR8898216 NaN NaN NaN NaN NaN NaN         NaN
3700002       0/1  ...  SRR8898216 NaN NaN NaN NaN NaN NaN         NaN
3700003       0/1  ...  SRR8898216 NaN NaN NaN NaN NaN NaN         NaN
3700004       0/1  ...  SRR8898216 NaN NaN NaN NaN NaN NaN         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
3700000         NaN                                        NaN
3700001         NaN                                        NaN
3700002         NaN                                        NaN
3700003         NaN                                        NaN
3700004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM         POS ID REF ALT     QUAL FILTER    DP   AF GEN[0].GT  \
3800000  chr19  13334394.0  .   C   T  2081.16      .  65.0  1.0       1/1
3800001  chr19  13334394.0  .   C   T  2081.16      .  65.0  1.0       1/1
3800002  chr19  13334394.0  .   C   T  2081.16      .  65.0  1.0       1/1
3800003  chr19  13334394.0  .   C   T  2081.16      .  65.0  1.0       1/1
3800004  chr19  13334394.0  .   C   T  2081.16      .  65.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
3800000  ...  SRR8898217 NaN NaN NaN NaN NaN NaN         NaN         NaN
3800001  ...  SRR8898217 NaN NaN NaN NaN NaN NaN         NaN         NaN
3800002  ...  SRR8898217 NaN NaN NaN NaN NaN NaN         NaN         NaN
3800003  ...  SRR8898217 NaN NaN NaN NaN NaN NaN         NaN         NaN
3800004  ...  SRR8898217 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
3800000                                        NaN
3800001                                        NaN
3800002                                        NaN
3800003                                        NaN
3800004                                        NaN

[5 rows x 30 columns]
         CHROM          POS ID      REF      ALT          QUAL FILTER      DP  \
3900000  chr11  124038635.0  .        G        A  3.119550e+04      .  1008.0
3900001  chr11  124038943.0  .  CCTGGGG  GCTTGGA  1.281790e+04      .   560.0
3900002  chr11  124038988.0  .        G        C  2.739200e+04      .   871.0
3900003  chr11  124137008.0  .        C        T  6.900970e-15      .    61.0
3900004  chr11  124137008.0  .        C        T  6.900970e-15      .    61.0

          AF GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
3900000  1.0       1/1  ...  SRR8898218 NaN NaN NaN NaN NaN NaN           .
3900001  1.0       1/1  ...  SRR8898218 NaN NaN NaN NaN NaN NaN           .
3900002  1.0       1/1  ...  SRR8898218 NaN NaN NaN NaN NaN NaN           .
3900003  0.0       0/0  ...  SRR8898218 NaN NaN NaN NaN NaN NaN           .
3900004  0.0       0/0  ...  SRR8898218 NaN NaN NaN NaN NaN NaN           .

         NMD[*].GENE  version https://git-lfs.github.com/spec/v1
3900000            .                                         NaN
3900001            .                                         NaN
3900002            .                                         NaN
3900003            .                                         NaN
3900004            .                                         NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
4000000  chr7  12215808.0  .   C   T   485.04      .   56.0  0.5       0/1
4000001  chr7  12215808.0  .   C   T   485.04      .   56.0  0.5       0/1
4000002  chr7  12215808.0  .   C   T   485.04      .   56.0  0.5       0/1
4000003  chr7  12215808.0  .   C   T   485.04      .   56.0  0.5       0/1
4000004  chr7  12229791.0  .   C   G  2198.74      .  199.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
4000000  ...  SRR8898218 NaN NaN NaN NaN NaN NaN           .            .
4000001  ...  SRR8898218 NaN NaN NaN NaN NaN NaN           .            .
4000002  ...  SRR8898218 NaN NaN NaN NaN NaN NaN           .            .
4000003  ...  SRR8898218 NaN NaN NaN NaN NaN NaN           .            .
4000004  ...  SRR8898218 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
4000000                                         NaN
4000001                                         NaN
4000002                                         NaN
4000003                                         NaN
4000004                                         NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT          QUAL FILTER    DP   AF  \
4100000  chr19  49666074.0  .   G   A  2.179550e-14      .  35.0  0.0
4100001  chr19  49666074.0  .   G   A  2.179550e-14      .  35.0  0.0
4100002  chr19  49666074.0  .   G   A  2.179550e-14      .  35.0  0.0
4100003  chr19  49666074.0  .   G   A  2.179550e-14      .  35.0  0.0
4100004  chr19  49666074.0  .   G   A  2.179550e-14      .  35.0  0.0

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
4100000       0/0  ...  SRR8898219 NaN NaN NaN NaN NaN NaN           .
4100001       0/0  ...  SRR8898219 NaN NaN NaN NaN NaN NaN           .
4100002       0/0  ...  SRR8898219 NaN NaN NaN NaN NaN NaN           .
4100003       0/0  ...  SRR8898219 NaN NaN NaN NaN NaN NaN           .
4100004       0/0  ...  SRR8898219 NaN NaN NaN NaN NaN NaN           .

         NMD[*].GENE  version https://git-lfs.github.com/spec/v1
4100000            .                                         NaN
4100001            .                                         NaN
4100002            .                                         NaN
4100003            .                                         NaN
4100004            .                                         NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT       QUAL FILTER     DP   AF GEN[0].GT  \
4200000  chr12  42441526.0  .  TA   T    19.2711      .   21.0  0.5       0/1
4200001  chr12  42446034.0  .   A   C  6729.8900      .  210.0  1.0       1/1
4200002  chr12  42446034.0  .   A   C  6729.8900      .  210.0  1.0       1/1
4200003  chr12  42446034.0  .   A   C  6729.8900      .  210.0  1.0       1/1
4200004  chr12  42446034.0  .   A   C  6729.8900      .  210.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
4200000  ...  SRR8898220 NaN NaN NaN NaN NaN NaN           .            .
4200001  ...  SRR8898220 NaN NaN NaN NaN NaN NaN           .            .
4200002  ...  SRR8898220 NaN NaN NaN NaN NaN NaN           .            .
4200003  ...  SRR8898220 NaN NaN NaN NaN NaN NaN           .            .
4200004  ...  SRR8898220 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
4200000                                         NaN
4200001                                         NaN
4200002                                         NaN
4200003                                         NaN
4200004                                         NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (27,28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

        CHROM          POS ID  REF  ALT          QUAL FILTER    DP   AF  \
4300000  chr7  100957340.0  .    C    A  5.760050e-09      .  44.0  0.5
4300001  chr7  100957346.0  .    C    T  7.792340e-09      .  44.0  0.5
4300002  chr7  100957346.0  .    C    T  7.792340e-09      .  44.0  0.5
4300003  chr7  100957361.0  .  ATA  GTG  4.868730e+00      .  40.0  0.5
4300004  chr7  100957361.0  .  ATA  GTG  4.868730e+00      .  40.0  0.5

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
4300000       0/1  ...  SRR8898220 NaN NaN NaN NaN NaN NaN           .
4300001       0/1  ...  SRR8898220 NaN NaN NaN NaN NaN NaN           .
4300002       0/1  ...  SRR8898220 NaN NaN NaN NaN NaN NaN           .
4300003       0/1  ...  SRR8898220 NaN NaN NaN NaN NaN NaN           .
4300004       0/1  ...  SRR8898220 NaN NaN NaN NaN NaN NaN           .

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
4300000           .                                        NaN
4300001           .                                        NaN
4300002           .                                        NaN
4300003           .                                        NaN
4300004           .                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT       QUAL FILTER     DP   AF GEN[0].GT  \
4400000  chr2  177552497.0  .   C   T   3353.650      .  112.0  1.0       1/1
4400001  chr2  177617090.0  .   G   T  22139.100      .  739.0  1.0       1/1
4400002  chr2  177617090.0  .   G   T  22139.100      .  739.0  1.0       1/1
4400003  chr2  177617366.0  .   C   T    840.357      .   35.0  1.0       1/1
4400004  chr2  177617366.0  .   C   T    840.357      .   35.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
4400000  ...  SRR8898222 NaN NaN NaN NaN NaN NaN         NaN         NaN
4400001  ...  SRR8898222 NaN NaN NaN NaN NaN NaN         NaN         NaN
4400002  ...  SRR8898222 NaN NaN NaN NaN NaN NaN         NaN         NaN
4400003  ...  SRR8898222 NaN NaN NaN NaN NaN NaN         NaN         NaN
4400004  ...  SRR8898222 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
4400000                                        NaN
4400001                                        NaN
4400002                                        NaN
4400003                                        NaN
4400004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT          QUAL FILTER     DP   AF  \
4500000  chr14  63599622.0  .   A   G  1.017370e-13      .  564.0  0.0
4500001  chr14  63599622.0  .   A   G  1.017370e-13      .  564.0  0.0
4500002  chr14  63599622.0  .   A   G  1.017370e-13      .  564.0  0.0
4500003  chr14  63599622.0  .   A   G  1.017370e-13      .  564.0  0.0
4500004  chr14  63599634.0  .   T   A  4.038140e-14      .  618.0  0.0

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
4500000       0/0  ...  SRR8898223 NaN NaN NaN NaN NaN NaN         NaN
4500001       0/0  ...  SRR8898223 NaN NaN NaN NaN NaN NaN         NaN
4500002       0/0  ...  SRR8898223 NaN NaN NaN NaN NaN NaN         NaN
4500003       0/0  ...  SRR8898223 NaN NaN NaN NaN NaN NaN         NaN
4500004       0/0  ...  SRR8898223 NaN NaN NaN NaN NaN NaN         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
4500000         NaN                                        NaN
4500001         NaN                                        NaN
4500002         NaN                                        NaN
4500003         NaN                                        NaN
4500004         NaN                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
4600000  chrX  104013669.0  .   G   A  6821.07      .  573.0  0.5       0/1
4600001  chrX  104013669.0  .   G   A  6821.07      .  573.0  0.5       0/1
4600002  chrX  104040193.0  .   C   T  2519.28      .  194.0  0.5       0/1
4600003  chrX  104040193.0  .   C   T  2519.28      .  194.0  0.5       0/1
4600004  chrX  104115158.0  .   C   T  8094.27      .  249.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
4600000  ...  SRR8898223 NaN NaN NaN NaN NaN NaN         NaN         NaN
4600001  ...  SRR8898223 NaN NaN NaN NaN NaN NaN         NaN         NaN
4600002  ...  SRR8898223 NaN NaN NaN NaN NaN NaN         NaN         NaN
4600003  ...  SRR8898223 NaN NaN NaN NaN NaN NaN         NaN         NaN
4600004  ...  SRR8898223 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
4600000                                        NaN
4600001                                        NaN
4600002                                        NaN
4600003                                        NaN
4600004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
4700000  chr22  19971950.0  .   C   T  22738.7      .  727.0  1.0       1/1
4700001  chr22  19971950.0  .   C   T  22738.7      .  727.0  1.0       1/1
4700002  chr22  19971950.0  .   C   T  22738.7      .  727.0  1.0       1/1
4700003  chr22  19971950.0  .   C   T  22738.7      .  727.0  1.0       1/1
4700004  chr22  19971950.0  .   C   T  22738.7      .  727.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
4700000  ...  SRR8898224 NaN NaN NaN NaN NaN NaN         NaN         NaN
4700001  ...  SRR8898224 NaN NaN NaN NaN NaN NaN         NaN         NaN
4700002  ...  SRR8898224 NaN NaN NaN NaN NaN NaN         NaN         NaN
4700003  ...  SRR8898224 NaN NaN NaN NaN NaN NaN         NaN         NaN
4700004  ...  SRR8898224 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
4700000                                        NaN
4700001                                        NaN
4700002                                        NaN
4700003                                        NaN
4700004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT    QUAL FILTER     DP   AF GEN[0].GT  \
4800000  chr15  55497712.0  .   C   T  2799.6      .  237.0  0.5       0/1
4800001  chr15  55497712.0  .   C   T  2799.6      .  237.0  0.5       0/1
4800002  chr15  55497712.0  .   C   T  2799.6      .  237.0  0.5       0/1
4800003  chr15  55497712.0  .   C   T  2799.6      .  237.0  0.5       0/1
4800004  chr15  55497712.0  .   C   T  2799.6      .  237.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
4800000  ...  SRR8898225 NaN NaN NaN NaN NaN NaN           .            .
4800001  ...  SRR8898225 NaN NaN NaN NaN NaN NaN           .            .
4800002  ...  SRR8898225 NaN NaN NaN NaN NaN NaN           .            .
4800003  ...  SRR8898225 NaN NaN NaN NaN NaN NaN           .            .
4800004  ...  SRR8898225 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
4800000                                         NaN
4800001                                         NaN
4800002                                         NaN
4800003                                         NaN
4800004                                         NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
4900000  chr9  99828760.0  .   A   G   774.998      .   67.0  0.5       0/1
4900001  chr9  99833403.0  .   C   T  7183.460      .  655.0  0.5       0/1
4900002  chr9  99833403.0  .   C   T  7183.460      .  655.0  0.5       0/1
4900003  chr9  99833403.0  .   C   T  7183.460      .  655.0  0.5       0/1
4900004  chr9  99833403.0  .   C   T  7183.460      .  655.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
4900000  ...  SRR8898225 NaN NaN NaN NaN NaN NaN           .            .
4900001  ...  SRR8898225 NaN NaN NaN NaN NaN NaN           .            .
4900002  ...  SRR8898225 NaN NaN NaN NaN NaN NaN           .            .
4900003  ...  SRR8898225 NaN NaN NaN NaN NaN NaN           .            .
4900004  ...  SRR8898225 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
4900000                                         NaN
4900001                                         NaN
4900002                                         NaN
4900003                                         NaN
4900004                                         NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
5000000  chr21  45909438.0  .   T   C   3890.84      .  307.0  0.5       0/1
5000001  chr21  45909438.0  .   T   C   3890.84      .  307.0  0.5       0/1
5000002  chr21  45909438.0  .   T   C   3890.84      .  307.0  0.5       0/1
5000003  chr21  45909438.0  .   T   C   3890.84      .  307.0  0.5       0/1
5000004  chr21  45991017.0  .   T   C  13458.10      .  412.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
5000000  ...  SRR8898226 NaN NaN NaN NaN NaN NaN           .            .
5000001  ...  SRR8898226 NaN NaN NaN NaN NaN NaN           .            .
5000002  ...  SRR8898226 NaN NaN NaN NaN NaN NaN           .            .
5000003  ...  SRR8898226 NaN NaN NaN NaN NaN NaN           .            .
5000004  ...  SRR8898226 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
5000000                                         NaN
5000001                                         NaN
5000002                                         NaN
5000003                                         NaN
5000004                                         NaN

[5 rows x 30 columns]
         CHROM         POS ID       REF ALT      QUAL FILTER   DP   AF  \
5100000  chr15  75443698.0  .         G   T  157.2780      .  6.0  1.0
5100001  chr15  75443698.0  .         G   T  157.2780      .  6.0  1.0
5100002  chr15  75443698.0  .         G   T  157.2780      .  6.0  1.0
5100003  chr15  75443698.0  .         G   T  157.2780      .  6.0  1.0
5100004  chr15  75448175.0  .  TAAAAAAA   T   92.5771      .  5.0  1.0

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
5100000       1/1  ...  SRR8898227 NaN NaN NaN NaN NaN NaN           .
5100001       1/1  ...  SRR8898227 NaN NaN NaN NaN NaN NaN           .
5100002       1/1  ...  SRR8898227 NaN NaN NaN NaN NaN NaN           .
5100003       1/1  ...  SRR8898227 NaN NaN NaN NaN NaN NaN           .
5100004       1/1  ...  SRR8898227 NaN NaN NaN NaN NaN NaN           .

         NMD[*].GENE  version https://git-lfs.github.com/spec/v1
5100000            .                                         NaN
5100001            .                                         NaN
5100002            .                                         NaN
5100003            .                                         NaN
5100004            .                                         NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

        CHROM          POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
5200000  chr9  131307992.0  .   C   T   5011.76      .  371.0  0.5       0/1
5200001  chr9  131308116.0  .   T   C   7465.28      .  544.0  0.5       0/1
5200002  chr9  131470928.0  .   T   C  20747.30      .  625.0  1.0       1/1
5200003  chr9  131470928.0  .   T   C  20747.30      .  625.0  1.0       1/1
5200004  chr9  131474936.0  .   C   G    916.76      .   93.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
5200000  ...  SRR8898227 NaN NaN NaN NaN NaN NaN           .           .
5200001  ...  SRR8898227 NaN NaN NaN NaN NaN NaN           .           .
5200002  ...  SRR8898227 NaN NaN NaN NaN NaN NaN           .           .
5200003  ...  SRR8898227 NaN NaN NaN NaN NaN NaN           .           .
5200004  ...  SRR8898227 NaN NaN NaN NaN NaN NaN           .           .

        version https://git-lfs.github.com/spec/v1
5200000                                        NaN
5200001                                        NaN
5200002                                        NaN
5200003                                        NaN
5200004                                        NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
5300000  chr3  58126761.0  .   C   T  1340.60      .   98.0  0.5       0/1
5300001  chr3  58126761.0  .   C   T  1340.60      .   98.0  0.5       0/1
5300002  chr3  58126761.0  .   C   T  1340.60      .   98.0  0.5       0/1
5300003  chr3  58126761.0  .   C   T  1340.60      .   98.0  0.5       0/1
5300004  chr3  58132828.0  .   G   A  3336.87      .  266.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
5300000  ...  SRR8898228 NaN NaN NaN NaN NaN NaN         NaN         NaN
5300001  ...  SRR8898228 NaN NaN NaN NaN NaN NaN         NaN         NaN
5300002  ...  SRR8898228 NaN NaN NaN NaN NaN NaN         NaN         NaN
5300003  ...  SRR8898228 NaN NaN NaN NaN NaN NaN         NaN         NaN
5300004  ...  SRR8898228 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
5300000                                        NaN
5300001                                        NaN
5300002                                        NaN
5300003                                        NaN
5300004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
5400000  chr17  44006699.0  .   T   C  1253.270      .  111.0  0.5       0/1
5400001  chr17  44006699.0  .   T   C  1253.270      .  111.0  0.5       0/1
5400002  chr17  44006699.0  .   T   C  1253.270      .  111.0  0.5       0/1
5400003  chr17  44023103.0  .   G   A   204.391      .   20.0  0.5       0/1
5400004  chr17  44023103.0  .   G   A   204.391      .   20.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
5400000  ...  SRR8898229 NaN NaN NaN NaN NaN NaN         NaN         NaN
5400001  ...  SRR8898229 NaN NaN NaN NaN NaN NaN         NaN         NaN
5400002  ...  SRR8898229 NaN NaN NaN NaN NaN NaN         NaN         NaN
5400003  ...  SRR8898229 NaN NaN NaN NaN NaN NaN         NaN         NaN
5400004  ...  SRR8898229 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
5400000                                        NaN
5400001                                        NaN
5400002                                        NaN
5400003                                        NaN
5400004                                        NaN

[5 rows x 30 columns]
         CHROM        POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
5500000  chr11  5778238.0  .   C   T  10897.0      .  330.0  1.0       1/1
5500001  chr11  5778238.0  .   C   T  10897.0      .  330.0  1.0       1/1
5500002  chr11  5788000.0  .   G   A  11684.6      .  352.0  1.0       1/1
5500003  chr11  5788000.0  .   G   A  11684.6      .  352.0  1.0       1/1
5500004  chr11  5788000.0  .   G   A  11684.6      .  352.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
5500000  ...  SRR8898230 NaN NaN NaN NaN NaN NaN         NaN         NaN
5500001  ...  SRR8898230 NaN NaN NaN NaN NaN NaN         NaN         NaN
5500002  ...  SRR8898230 NaN NaN NaN NaN NaN NaN         NaN         NaN
5500003  ...  SRR8898230 NaN NaN NaN NaN NaN NaN         NaN         NaN
5500004  ...  SRR8898230 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
5500000                                        NaN
5500001                                        NaN
5500002                                        NaN
5500003                                        NaN
5500004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

        CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
5600000  chr7  44572748.0  .   G   C  19635.70      .  593.0  1.0       1/1
5600001  chr7  44572748.0  .   G   C  19635.70      .  593.0  1.0       1/1
5600002  chr7  44581237.0  .   C   A   3112.12      .  105.0  1.0       1/1
5600003  chr7  44581237.0  .   C   A   3112.12      .  105.0  1.0       1/1
5600004  chr7  44581237.0  .   C   A   3112.12      .  105.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
5600000  ...  SRR8898230 NaN NaN NaN NaN NaN NaN         NaN         NaN
5600001  ...  SRR8898230 NaN NaN NaN NaN NaN NaN         NaN         NaN
5600002  ...  SRR8898230 NaN NaN NaN NaN NaN NaN         NaN         NaN
5600003  ...  SRR8898230 NaN NaN NaN NaN NaN NaN         NaN         NaN
5600004  ...  SRR8898230 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
5600000                                        NaN
5600001                                        NaN
5600002                                        NaN
5600003                                        NaN
5600004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
5700000  chr19  51454302.0  .   T   C   944.539      .   32.0  1.0       1/1
5700001  chr19  51454302.0  .   T   C   944.539      .   32.0  1.0       1/1
5700002  chr19  51481471.0  .   T   A  5302.880      .  458.0  0.5       0/1
5700003  chr19  51497370.0  .   T   G  2812.960      .   89.0  1.0       1/1
5700004  chr19  51497370.0  .   T   G  2812.960      .   89.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
5700000  ...  SRR8898231 NaN NaN NaN NaN NaN NaN           .            .
5700001  ...  SRR8898231 NaN NaN NaN NaN NaN NaN           .            .
5700002  ...  SRR8898231 NaN NaN NaN NaN NaN NaN           .            .
5700003  ...  SRR8898231 NaN NaN NaN NaN NaN NaN           .            .
5700004  ...  SRR8898231 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
5700000                                         NaN
5700001                                         NaN
5700002                                         NaN
5700003                                         NaN
5700004                                         NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT          QUAL FILTER     DP   AF  \
5800000  chr12  32843190.0  .   T   C  7.841430e-10      .   25.0  0.0
5800001  chr12  32843205.0  .   A   T  1.796060e-14      .   35.0  0.0
5800002  chr12  32843205.0  .   A   T  1.796060e-14      .   35.0  0.0
5800003  chr12  32869000.0  .   A   G  2.048540e+03      .  170.0  0.5
5800004  chr12  32869000.0  .   A   G  2.048540e+03      .  170.0  0.5

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
5800000       0/0  ...  SRR8898232 NaN NaN NaN NaN NaN NaN           .
5800001       0/0  ...  SRR8898232 NaN NaN NaN NaN NaN NaN           .
5800002       0/0  ...  SRR8898232 NaN NaN NaN NaN NaN NaN           .
5800003       0/1  ...  SRR8898232 NaN NaN NaN NaN NaN NaN           .
5800004       0/1  ...  SRR8898232 NaN NaN NaN NaN NaN NaN           .

         NMD[*].GENE  version https://git-lfs.github.com/spec/v1
5800000            .                                         NaN
5800001            .                                         NaN
5800002            .                                         NaN
5800003            .                                         NaN
5800004            .                                         NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT          QUAL FILTER    DP   AF  \
5900000  chr7  76483031.0  .   C   G  5.032580e-15      .  99.0  0.0
5900001  chr7  76483031.0  .   C   G  5.032580e-15      .  99.0  0.0
5900002  chr7  76483031.0  .   C   G  5.032580e-15      .  99.0  0.0
5900003  chr7  76483031.0  .   C   G  5.032580e-15      .  99.0  0.0
5900004  chr7  76483031.0  .   C   G  5.032580e-15      .  99.0  0.0

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
5900000       0/0  ...  SRR8898232 NaN NaN NaN NaN NaN NaN           .
5900001       0/0  ...  SRR8898232 NaN NaN NaN NaN NaN NaN           .
5900002       0/0  ...  SRR8898232 NaN NaN NaN NaN NaN NaN           .
5900003       0/0  ...  SRR8898232 NaN NaN NaN NaN NaN NaN           .
5900004       0/0  ...  SRR8898232 NaN NaN NaN NaN NaN NaN           .

         NMD[*].GENE  version https://git-lfs.github.com/spec/v1
5900000            .                                         NaN
5900001            .                                         NaN
5900002            .                                         NaN
5900003            .                                         NaN
5900004            .                                         NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT       QUAL FILTER     DP   AF GEN[0].GT  \
6000000  chr19  49928131.0  .   G   A    48.7135      .    5.0  0.5       0/1
6000001  chr19  49928131.0  .   G   A    48.7135      .    5.0  0.5       0/1
6000002  chr19  49928131.0  .   G   A    48.7135      .    5.0  0.5       0/1
6000003  chr19  49932490.0  .   T   C  1494.1000      .  179.0  0.5       0/1
6000004  chr19  49932490.0  .   T   C  1494.1000      .  179.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
6000000  ...  SRR8898233 NaN NaN NaN NaN NaN NaN           .            .
6000001  ...  SRR8898233 NaN NaN NaN NaN NaN NaN           .            .
6000002  ...  SRR8898233 NaN NaN NaN NaN NaN NaN           .            .
6000003  ...  SRR8898233 NaN NaN NaN NaN NaN NaN           .            .
6000004  ...  SRR8898233 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
6000000                                         NaN
6000001                                         NaN
6000002                                         NaN
6000003                                         NaN
6000004                                         NaN

[5 rows x 30 columns]
         CHROM        POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
6100000  chr12  6727686.0  .   A   G  28931.8      .  871.0  1.0       1/1
6100001  chr12  6727686.0  .   A   G  28931.8      .  871.0  1.0       1/1
6100002  chr12  6727686.0  .   A   G  28931.8      .  871.0  1.0       1/1
6100003  chr12  6727686.0  .   A   G  28931.8      .  871.0  1.0       1/1
6100004  chr12  6727686.0  .   A   G  28931.8      .  871.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
6100000  ...  SRR8898234 NaN NaN NaN NaN NaN NaN           .            .
6100001  ...  SRR8898234 NaN NaN NaN NaN NaN NaN           .            .
6100002  ...  SRR8898234 NaN NaN NaN NaN NaN NaN           .            .
6100003  ...  SRR8898234 NaN NaN NaN NaN NaN NaN           .            .
6100004  ...  SRR8898234 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
6100000                                         NaN
6100001                                         NaN
6100002                                         NaN
6100003                                         NaN
6100004                                         NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

        CHROM          POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
6200000  chr7  113879741.0  .   C   T  14081.00      .  425.0  1.0       1/1
6200001  chr7  114979543.0  .   C   A   6793.41      .  209.0  1.0       1/1
6200002  chr7  114979543.0  .   C   A   6793.41      .  209.0  1.0       1/1
6200003  chr7  114979543.0  .   C   A   6793.41      .  209.0  1.0       1/1
6200004  chr7  114979543.0  .   C   A   6793.41      .  209.0  1.0       1/1

         ...   Sample_ID  AB   GQ  AO  RO   GT   AD LOF[*].GENE NMD[*].GENE  \
6200000  ...  SRR8898234 NaN  NaN NaN NaN  NaN  NaN           .           .
6200001  ...  SRR8898234 NaN  NaN NaN NaN  NaN  NaN           .           .
6200002  ...  SRR8898234 NaN  NaN NaN NaN  NaN  NaN           .           .
6200003  ...  SRR8898234 NaN  NaN NaN NaN  NaN  NaN           .           .
6200004  ...  SRR8898234 NaN  NaN NaN NaN  NaN  NaN           .           .

        version https://git-lfs.github.com/spec/v1
6200000                                        NaN
6200001                                        NaN
6200002                                        NaN
6200003                                        NaN
6200004                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT      QUAL FILTER     DP   AF  GEN[0].GT  \
6300000  chr2  238131702.0  .   G   A   8246.98      .  651.0  0.5        NaN
6300001  chr2  238131702.0  .   G   A   8246.98      .  651.0  0.5        NaN
6300002  chr2  238131702.0  .   G   A   8246.98      .  651.0  0.5        NaN
6300003  chr2  238132067.0  .   C   A  14236.70      .  438.0  1.0        NaN
6300004  chr2  238132067.0  .   C   A  14236.70      .  438.0  1.0        NaN

         ...   Sample_ID        AB GQ     AO     RO  GT AD LOF[*].GENE  \
6300000  ...  SRR8898235  0.480799  .  313.0  338.0   .  .         NaN
6300001  ...  SRR8898235  0.480799  .  313.0  338.0   .  .         NaN
6300002  ...  SRR8898235  0.480799  .  313.0  338.0   .  .         NaN
6300003  ...  SRR8898235  0.000000  .  437.0    0.0   .  .         NaN
6300004  ...  SRR8898235  0.000000  .  437.0    0.0   .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
6300000         NaN                                        NaN
6300001         NaN                                        NaN
6300002         NaN                                        NaN
6300003         NaN                                        NaN
6300004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,22,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM       POS ID REF ALT    QUAL FILTER     DP   AF GEN[0].GT  ...  \
6400000  chr16  728820.0  .   G   A  4747.0      .  453.0  0.5       NaN  ...
6400001  chr16  728820.0  .   G   A  4747.0      .  453.0  0.5       NaN  ...
6400002  chr16  728820.0  .   G   A  4747.0      .  453.0  0.5       NaN  ...
6400003  chr16  728820.0  .   G   A  4747.0      .  453.0  0.5       NaN  ...
6400004  chr16  728820.0  .   G   A  4747.0      .  453.0  0.5       NaN  ...

          Sample_ID        AB GQ     AO     RO GT AD LOF[*].GENE NMD[*].GENE  \
6400000  SRR8898236  0.421634  .  191.0  262.0  .  .         NaN         NaN
6400001  SRR8898236  0.421634  .  191.0  262.0  .  .         NaN         NaN
6400002  SRR8898236  0.421634  .  191.0  262.0  .  .         NaN         NaN
6400003  SRR8898236  0.421634  .  191.0  262.0  .  .         NaN         NaN
6400004  SRR8898236  0.421634  .  191.0  262.0  .  .         NaN         NaN

        version https://git-lfs.github.com/spec/v1
6400000                                        NaN
6400001                                        NaN
6400002                                        NaN
6400003                                        NaN
6400004                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
6500000  chr1  147201324.0  .   T   C  8611.70      .  590.0  0.5       0/1
6500001  chr1  147201324.0  .   T   C  8611.70      .  590.0  0.5       0/1
6500002  chr1  147201324.0  .   T   C  8611.70      .  590.0  0.5       0/1
6500003  chr1  147242742.0  .   C   G  1745.54      .  129.0  0.5       0/1
6500004  chr1  147242742.0  .   C   G  1745.54      .  129.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
6500000  ...  SRR8898237 NaN NaN NaN NaN NaN NaN         NaN         NaN
6500001  ...  SRR8898237 NaN NaN NaN NaN NaN NaN         NaN         NaN
6500002  ...  SRR8898237 NaN NaN NaN NaN NaN NaN         NaN         NaN
6500003  ...  SRR8898237 NaN NaN NaN NaN NaN NaN         NaN         NaN
6500004  ...  SRR8898237 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
6500000                                        NaN
6500001                                        NaN
6500002                                        NaN
6500003                                        NaN
6500004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

        CHROM        POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
6600000  chr5  6651896.0  .   G   A  1299.74      .   99.0  0.5       0/1
6600001  chr5  6651896.0  .   G   A  1299.74      .   99.0  0.5       0/1
6600002  chr5  6651896.0  .   G   A  1299.74      .   99.0  0.5       0/1
6600003  chr5  6652016.0  .   T   C  3649.85      .  246.0  0.5       0/1
6600004  chr5  6652016.0  .   T   C  3649.85      .  246.0  0.5       0/1

         ...   Sample_ID  AB   GQ  AO  RO   GT   AD LOF[*].GENE NMD[*].GENE  \
6600000  ...  SRR8898237 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
6600001  ...  SRR8898237 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
6600002  ...  SRR8898237 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
6600003  ...  SRR8898237 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
6600004  ...  SRR8898237 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
6600000                                        NaN
6600001                                        NaN
6600002                                        NaN
6600003                                        NaN
6600004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,18,19,22,25,26,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
6700000  chr19  32864175.0  .   G   A  6639.34      .  463.0  0.5       NaN
6700001  chr19  32864175.0  .   G   A  6639.34      .  463.0  0.5       NaN
6700002  chr19  32864175.0  .   G   A  6639.34      .  463.0  0.5       NaN
6700003  chr19  32899890.0  .   G   A  7359.23      .  581.0  0.5       NaN
6700004  chr19  32899890.0  .   G   A  7359.23      .  581.0  0.5       NaN

         ...   Sample_ID        AB GQ     AO     RO GT AD LOF[*].GENE  \
6700000  ...  SRR8898238  0.542117  .  251.0  212.0  .  .         NaN
6700001  ...  SRR8898238  0.542117  .  251.0  212.0  .  .         NaN
6700002  ...  SRR8898238  0.542117  .  251.0  212.0  .  .         NaN
6700003  ...  SRR8898238  0.475043  .  276.0  304.0  .  .         NaN
6700004  ...  SRR8898238  0.475043  .  276.0  304.0  .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
6700000         NaN                                        NaN
6700001         NaN                                        NaN
6700002         NaN                                        NaN
6700003         NaN                                        NaN
6700004         NaN                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
6800000  chr12  56719388.0  .   G   A  3809.51      .  276.0  0.5       0/1
6800001  chr12  56719388.0  .   G   A  3809.51      .  276.0  0.5       0/1
6800002  chr12  56719388.0  .   G   A  3809.51      .  276.0  0.5       0/1
6800003  chr12  56719388.0  .   G   A  3809.51      .  276.0  0.5       0/1
6800004  chr12  56719388.0  .   G   A  3809.51      .  276.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
6800000  ...  SRR8898239 NaN NaN NaN NaN NaN NaN           .            .
6800001  ...  SRR8898239 NaN NaN NaN NaN NaN NaN           .            .
6800002  ...  SRR8898239 NaN NaN NaN NaN NaN NaN           .            .
6800003  ...  SRR8898239 NaN NaN NaN NaN NaN NaN           .            .
6800004  ...  SRR8898239 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
6800000                                         NaN
6800001                                         NaN
6800002                                         NaN
6800003                                         NaN
6800004                                         NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT    QUAL FILTER   DP   AF GEN[0].GT  ...  \
6900000  chr7  101244552.0  .   C   A  10.581      .  8.0  0.5       0/1  ...
6900001  chr7  101244552.0  .   C   A  10.581      .  8.0  0.5       0/1  ...
6900002  chr7  101244552.0  .   C   A  10.581      .  8.0  0.5       0/1  ...
6900003  chr7  101244552.0  .   C   A  10.581      .  8.0  0.5       0/1  ...
6900004  chr7  101244552.0  .   C   A  10.581      .  8.0  0.5       0/1  ...

          Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
6900000  SRR8898239 NaN NaN NaN NaN NaN NaN           .            .
6900001  SRR8898239 NaN NaN NaN NaN NaN NaN           .            .
6900002  SRR8898239 NaN NaN NaN NaN NaN NaN           .            .
6900003  SRR8898239 NaN NaN NaN NaN NaN NaN           .            .
6900004  SRR8898239 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
6900000                                         NaN
6900001                                         NaN
6900002                                         NaN
6900003                                         NaN
6900004                                         NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
7000000  chr2  55177789.0  .   C   T  5094.48      .  150.0  1.0       1/1
7000001  chr2  55177789.0  .   C   T  5094.48      .  150.0  1.0       1/1
7000002  chr2  55177789.0  .   C   T  5094.48      .  150.0  1.0       1/1
7000003  chr2  55177789.0  .   C   T  5094.48      .  150.0  1.0       1/1
7000004  chr2  55177789.0  .   C   T  5094.48      .  150.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
7000000  ...  SRR8898240 NaN NaN NaN NaN NaN NaN           .            .
7000001  ...  SRR8898240 NaN NaN NaN NaN NaN NaN           .            .
7000002  ...  SRR8898240 NaN NaN NaN NaN NaN NaN           .            .
7000003  ...  SRR8898240 NaN NaN NaN NaN NaN NaN           .            .
7000004  ...  SRR8898240 NaN NaN NaN NaN NaN NaN           .            .

         version https://git-lfs.github.com/spec/v1
7000000                                         NaN
7000001                                         NaN
7000002                                         NaN
7000003                                         NaN
7000004                                         NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT          QUAL FILTER    DP   AF  \
7100000  chr12  57771136.0  .   C   A  4.475110e-14      .  40.0  0.0
7100001  chr12  57771136.0  .   C   A  4.475110e-14      .  40.0  0.0
7100002  chr12  57771136.0  .   C   A  4.475110e-14      .  40.0  0.0
7100003  chr12  57783596.0  .  CT   C  1.699620e-08      .  42.0  0.5
7100004  chr12  57783596.0  .  CT   C  1.699620e-08      .  42.0  0.5

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
7100000       0/0  ...  SRR8898241 NaN NaN NaN NaN NaN NaN           .
7100001       0/0  ...  SRR8898241 NaN NaN NaN NaN NaN NaN           .
7100002       0/0  ...  SRR8898241 NaN NaN NaN NaN NaN NaN           .
7100003       0/1  ...  SRR8898241 NaN NaN NaN NaN NaN NaN           .
7100004       0/1  ...  SRR8898241 NaN NaN NaN NaN NaN NaN           .

         NMD[*].GENE  version https://git-lfs.github.com/spec/v1
7100000            .                                         NaN
7100001            .                                         NaN
7100002            .                                         NaN
7100003            .                                         NaN
7100004            .                                         NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

        CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
7200000  chr7  76000956.0  .   T   C  16483.5      .  515.0  1.0       1/1
7200001  chr7  76000956.0  .   T   C  16483.5      .  515.0  1.0       1/1
7200002  chr7  76000956.0  .   T   C  16483.5      .  515.0  1.0       1/1
7200003  chr7  76000956.0  .   T   C  16483.5      .  515.0  1.0       1/1
7200004  chr7  76000956.0  .   T   C  16483.5      .  515.0  1.0       1/1

         ...   Sample_ID  AB   GQ  AO  RO   GT   AD LOF[*].GENE NMD[*].GENE  \
7200000  ...  SRR8898241 NaN  NaN NaN NaN  NaN  NaN           .           .
7200001  ...  SRR8898241 NaN  NaN NaN NaN  NaN  NaN           .           .
7200002  ...  SRR8898241 NaN  NaN NaN NaN  NaN  NaN           .           .
7200003  ...  SRR8898241 NaN  NaN NaN NaN  NaN  NaN           .           .
7200004  ...  SRR8898241 NaN  NaN NaN NaN  NaN  NaN           .           .

        version https://git-lfs.github.com/spec/v1
7200000                                        NaN
7200001                                        NaN
7200002                                        NaN
7200003                                        NaN
7200004                                        NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT    QUAL FILTER      DP   AF  GEN[0].GT  \
7300000  chr2  95935616.0  .   C   T  1051.4      .   151.0  0.5        NaN
7300001  chr2  95935616.0  .   C   T  1051.4      .   151.0  0.5        NaN
7300002  chr2  95938828.0  .   C   T     0.0      .  2597.0  0.0        NaN
7300003  chr2  95938828.0  .   C   T     0.0      .  2597.0  0.0        NaN
7300004  chr2  95938828.0  .   C   T     0.0      .  2597.0  0.0        NaN

         ...   Sample_ID        AB GQ     AO      RO  GT AD LOF[*].GENE  \
7300000  ...  SRR8898242  0.496689  .   75.0    76.0   .  .         NaN
7300001  ...  SRR8898242  0.496689  .   75.0    76.0   .  .         NaN
7300002  ...  SRR8898242  0.000000  .  167.0  2429.0   .  .         NaN
7300003  ...  SRR8898242  0.000000  .  167.0  2429.0   .  .         NaN
7300004  ...  SRR8898242  0.000000  .  167.0  2429.0   .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
7300000         NaN                                        NaN
7300001         NaN                                        NaN
7300002         NaN                                        NaN
7300003         NaN                                        NaN
7300004         NaN                                        NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT     QUAL FILTER    DP   AF  GEN[0].GT  \
7400000  chr14  103519918.0  .   C   T  804.804      .  52.0  0.5        NaN
7400001  chr14  103521843.0  .   G   T  487.462      .  59.0  0.5        NaN
7400002  chr14  103521843.0  .   G   T  487.462      .  59.0  0.5        NaN
7400003  chr14  103521843.0  .   G   T  487.462      .  59.0  0.5        NaN
7400004  chr14  103521843.0  .   G   T  487.462      .  59.0  0.5        NaN

         ...   Sample_ID        AB GQ    AO    RO  GT AD LOF[*].GENE  \
7400000  ...  SRR8898243  0.596154  .  31.0  21.0   .  .         NaN
7400001  ...  SRR8898243  0.440678  .  26.0  33.0   .  .         NaN
7400002  ...  SRR8898243  0.440678  .  26.0  33.0   .  .         NaN
7400003  ...  SRR8898243  0.440678  .  26.0  33.0   .  .         NaN
7400004  ...  SRR8898243  0.440678  .  26.0  33.0   .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
7400000         NaN                                        NaN
7400001         NaN                                        NaN
7400002         NaN                                        NaN
7400003         NaN                                        NaN
7400004         NaN                                        NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT          QUAL FILTER     DP   AF  \
7500000  chr1  36088072.0  .   A   G  2.317670e+04      .  675.0  1.0
7500001  chr1  36178156.0  .   C   G  1.777960e-14      .   39.0  0.0
7500002  chr1  36178156.0  .   C   G  1.777960e-14      .   39.0  0.0
7500003  chr1  36178156.0  .   C   G  1.777960e-14      .   39.0  0.0
7500004  chr1  36178156.0  .   C   G  1.777960e-14      .   39.0  0.0

         GEN[0].GT  ...   Sample_ID   AB GQ     AO    RO  GT AD LOF[*].GENE  \
7500000        NaN  ...  SRR8898244  0.0  .  675.0   0.0   .  .         NaN
7500001        NaN  ...  SRR8898244  0.0  .    2.0  37.0   .  .         NaN
7500002        NaN  ...  SRR8898244  0.0  .    2.0  37.0   .  .         NaN
7500003        NaN  ...  SRR8898244  0.0  .    2.0  37.0   .  .         NaN
7500004        NaN  ...  SRR8898244  0.0  .    2.0  37.0   .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
7500000         NaN                                        NaN
7500001         NaN                                        NaN
7500002         NaN                                        NaN
7500003         NaN                                        NaN
7500004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,22,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

        CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
7600000  chr4  82901181.0  .   G   A   2015.03      .  161.0  0.5       NaN
7600001  chr4  82901181.0  .   G   A   2015.03      .  161.0  0.5       NaN
7600002  chr4  82901181.0  .   G   A   2015.03      .  161.0  0.5       NaN
7600003  chr4  82917064.0  .   G   A  24451.30      .  700.0  1.0       NaN
7600004  chr4  82917064.0  .   G   A  24451.30      .  700.0  1.0       NaN

         ...   Sample_ID        AB GQ     AO    RO GT AD LOF[*].GENE  \
7600000  ...  SRR8898244  0.465839  .   75.0  86.0  .  .         NaN
7600001  ...  SRR8898244  0.465839  .   75.0  86.0  .  .         NaN
7600002  ...  SRR8898244  0.465839  .   75.0  86.0  .  .         NaN
7600003  ...  SRR8898244  0.000000  .  700.0   0.0  .  .         NaN
7600004  ...  SRR8898244  0.000000  .  700.0   0.0  .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
7600000         NaN                                        NaN
7600001         NaN                                        NaN
7600002         NaN                                        NaN
7600003         NaN                                        NaN
7600004         NaN                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT          QUAL FILTER    DP   AF  \
7700000  chr13  20631053.0  .   G   A  1.576100e+03      .  47.0  1.0
7700001  chr13  20638343.0  .   T   G  6.250050e-14      .  35.0  0.0
7700002  chr13  20638343.0  .   T   G  6.250050e-14      .  35.0  0.0
7700003  chr13  20638343.0  .   T   G  6.250050e-14      .  35.0  0.0
7700004  chr13  20638343.0  .   T   G  6.250050e-14      .  35.0  0.0

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
7700000       1/1  ...  SRR8898245 NaN NaN NaN NaN NaN NaN         NaN
7700001       0/0  ...  SRR8898245 NaN NaN NaN NaN NaN NaN         NaN
7700002       0/0  ...  SRR8898245 NaN NaN NaN NaN NaN NaN         NaN
7700003       0/0  ...  SRR8898245 NaN NaN NaN NaN NaN NaN         NaN
7700004       0/0  ...  SRR8898245 NaN NaN NaN NaN NaN NaN         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
7700000         NaN                                        NaN
7700001         NaN                                        NaN
7700002         NaN                                        NaN
7700003         NaN                                        NaN
7700004         NaN                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT      QUAL FILTER    DP   AF GEN[0].GT  \
7800000  chr22  20518967.0  .   G   C  0.483317      .  14.0  0.5       0/1
7800001  chr22  20518967.0  .   G   C  0.483317      .  14.0  0.5       0/1
7800002  chr22  20518967.0  .   G   C  0.483317      .  14.0  0.5       0/1
7800003  chr22  20518967.0  .   G   C  0.483317      .  14.0  0.5       0/1
7800004  chr22  20518967.0  .   G   C  0.483317      .  14.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
7800000  ...  SRR8898245 NaN NaN NaN NaN NaN NaN         NaN         NaN
7800001  ...  SRR8898245 NaN NaN NaN NaN NaN NaN         NaN         NaN
7800002  ...  SRR8898245 NaN NaN NaN NaN NaN NaN         NaN         NaN
7800003  ...  SRR8898245 NaN NaN NaN NaN NaN NaN         NaN         NaN
7800004  ...  SRR8898245 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
7800000                                        NaN
7800001                                        NaN
7800002                                        NaN
7800003                                        NaN
7800004                                        NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
7900000  chr1  86126154.0  .   G   A  13419.20      .  413.0  1.0       1/1
7900001  chr1  86126154.0  .   G   A  13419.20      .  413.0  1.0       1/1
7900002  chr1  86352889.0  .   T   C   2246.62      .  177.0  0.5       0/1
7900003  chr1  86352889.0  .   T   C   2246.62      .  177.0  0.5       0/1
7900004  chr1  86352889.0  .   T   C   2246.62      .  177.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
7900000  ...  SRR8898246 NaN NaN NaN NaN NaN NaN         NaN         NaN
7900001  ...  SRR8898246 NaN NaN NaN NaN NaN NaN         NaN         NaN
7900002  ...  SRR8898246 NaN NaN NaN NaN NaN NaN         NaN         NaN
7900003  ...  SRR8898246 NaN NaN NaN NaN NaN NaN         NaN         NaN
7900004  ...  SRR8898246 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
7900000                                        NaN
7900001                                        NaN
7900002                                        NaN
7900003                                        NaN
7900004                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT         QUAL FILTER     DP   AF  \
8000000  chr4  119030492.0  .   A   G  8873.680000      .  750.0  0.5
8000001  chr4  119030492.0  .   A   G  8873.680000      .  750.0  0.5
8000002  chr4  119061244.0  .   T   A     0.000002      .   21.0  0.5
8000003  chr4  119061244.0  .   T   A     0.000002      .   21.0  0.5
8000004  chr4  119061244.0  .   T   A     0.000002      .   21.0  0.5

        GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
8000000       0/1  ...  SRR8898246 NaN NaN NaN NaN NaN NaN         NaN
8000001       0/1  ...  SRR8898246 NaN NaN NaN NaN NaN NaN         NaN
8000002       0/1  ...  SRR8898246 NaN NaN NaN NaN NaN NaN         NaN
8000003       0/1  ...  SRR8898246 NaN NaN NaN NaN NaN NaN         NaN
8000004       0/1  ...  SRR8898246 NaN NaN NaN NaN NaN NaN         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
8000000         NaN                                        NaN
8000001         NaN                                        NaN
8000002         NaN                                        NaN
8000003         NaN                                        NaN
8000004         NaN                                        NaN

[5 rows x 30 columns]
         CHROM        POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
8100000  chr19  8335767.0  .   C   G  1267.74      .   79.0  0.5       0/1
8100001  chr19  8371280.0  .   C   T  4530.37      .  305.0  0.5       0/1
8100002  chr19  8371280.0  .   C   T  4530.37      .  305.0  0.5       0/1
8100003  chr19  8371280.0  .   C   T  4530.37      .  305.0  0.5       0/1
8100004  chr19  8371280.0  .   C   T  4530.37      .  305.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
8100000  ...  SRR8898247 NaN NaN NaN NaN NaN NaN         NaN         NaN
8100001  ...  SRR8898247 NaN NaN NaN NaN NaN NaN         NaN         NaN
8100002  ...  SRR8898247 NaN NaN NaN NaN NaN NaN         NaN         NaN
8100003  ...  SRR8898247 NaN NaN NaN NaN NaN NaN         NaN         NaN
8100004  ...  SRR8898247 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
8100000                                        NaN
8100001                                        NaN
8100002                                        NaN
8100003                                        NaN
8100004                                        NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
8200000  chr11  125896149.0  .   C   A   7698.44      .  612.0  0.5       0/1
8200001  chr11  125896149.0  .   C   A   7698.44      .  612.0  0.5       0/1
8200002  chr11  125896149.0  .   C   A   7698.44      .  612.0  0.5       0/1
8200003  chr11  125896278.0  .   A   C  11319.50      .  339.0  1.0       1/1
8200004  chr11  125896278.0  .   A   C  11319.50      .  339.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
8200000  ...  SRR8898248 NaN NaN NaN NaN NaN NaN         NaN         NaN
8200001  ...  SRR8898248 NaN NaN NaN NaN NaN NaN         NaN         NaN
8200002  ...  SRR8898248 NaN NaN NaN NaN NaN NaN         NaN         NaN
8200003  ...  SRR8898248 NaN NaN NaN NaN NaN NaN         NaN         NaN
8200004  ...  SRR8898248 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
8200000                                        NaN
8200001                                        NaN
8200002                                        NaN
8200003                                        NaN
8200004                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
8300000  chr7  107185936.0  .   C   T  3884.38      .  343.0  0.5       0/1
8300001  chr7  107185936.0  .   C   T  3884.38      .  343.0  0.5       0/1
8300002  chr7  107185936.0  .   C   T  3884.38      .  343.0  0.5       0/1
8300003  chr7  107185936.0  .   C   T  3884.38      .  343.0  0.5       0/1
8300004  chr7  107256792.0  .   A   C  1704.15      .  114.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
8300000  ...  SRR8898248 NaN NaN NaN NaN NaN NaN         NaN         NaN
8300001  ...  SRR8898248 NaN NaN NaN NaN NaN NaN         NaN         NaN
8300002  ...  SRR8898248 NaN NaN NaN NaN NaN NaN         NaN         NaN
8300003  ...  SRR8898248 NaN NaN NaN NaN NaN NaN         NaN         NaN
8300004  ...  SRR8898248 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
8300000                                        NaN
8300001                                        NaN
8300002                                        NaN
8300003                                        NaN
8300004                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
8400000  chr2  233693556.0  .   A   C  13380.9      .  401.0  1.0       1/1
8400001  chr2  233693556.0  .   A   C  13380.9      .  401.0  1.0       1/1
8400002  chr2  233693556.0  .   A   C  13380.9      .  401.0  1.0       1/1
8400003  chr2  233693556.0  .   A   C  13380.9      .  401.0  1.0       1/1
8400004  chr2  233693556.0  .   A   C  13380.9      .  401.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
8400000  ...  SRR8898249 NaN NaN NaN NaN NaN NaN         NaN         NaN
8400001  ...  SRR8898249 NaN NaN NaN NaN NaN NaN         NaN         NaN
8400002  ...  SRR8898249 NaN NaN NaN NaN NaN NaN         NaN         NaN
8400003  ...  SRR8898249 NaN NaN NaN NaN NaN NaN         NaN         NaN
8400004  ...  SRR8898249 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
8400000                                        NaN
8400001                                        NaN
8400002                                        NaN
8400003                                        NaN
8400004                                        NaN

[5 rows x 30 columns]
         CHROM       POS ID REF ALT    QUAL FILTER     DP   AF GEN[0].GT  ...  \
8500000  chr16  377479.0  .   T   C  5650.1      .  174.0  1.0       1/1  ...
8500001  chr16  377516.0  .   T   C  7528.9      .  224.0  1.0       1/1  ...
8500002  chr16  377516.0  .   T   C  7528.9      .  224.0  1.0       1/1  ...
8500003  chr16  377516.0  .   T   C  7528.9      .  224.0  1.0       1/1  ...
8500004  chr16  377516.0  .   T   C  7528.9      .  224.0  1.0       1/1  ...

          Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
8500000  SRR8898250 NaN NaN NaN NaN NaN NaN         NaN         NaN
8500001  SRR8898250 NaN NaN NaN NaN NaN NaN         NaN         NaN
8500002  SRR8898250 NaN NaN NaN NaN NaN NaN         NaN         NaN
8500003  SRR8898250 NaN NaN NaN NaN NaN NaN         NaN         NaN
8500004  SRR8898250 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
8500000                                        NaN
8500001                                        NaN
8500002                                        NaN
8500003                                        NaN
8500004                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT     QUAL FILTER    DP   AF GEN[0].GT  \
8600000  chr1  146991176.0  .   T   G  13.2503      .  11.0  0.5       0/1
8600001  chr1  146991176.0  .   T   G  13.2503      .  11.0  0.5       0/1
8600002  chr1  146991176.0  .   T   G  13.2503      .  11.0  0.5       0/1
8600003  chr1  146991176.0  .   T   G  13.2503      .  11.0  0.5       0/1
8600004  chr1  146991176.0  .   T   G  13.2503      .  11.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
8600000  ...  SRR8898251 NaN NaN NaN NaN NaN NaN         NaN         NaN
8600001  ...  SRR8898251 NaN NaN NaN NaN NaN NaN         NaN         NaN
8600002  ...  SRR8898251 NaN NaN NaN NaN NaN NaN         NaN         NaN
8600003  ...  SRR8898251 NaN NaN NaN NaN NaN NaN         NaN         NaN
8600004  ...  SRR8898251 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
8600000                                        NaN
8600001                                        NaN
8600002                                        NaN
8600003                                        NaN
8600004                                        NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT       QUAL FILTER     DP   AF GEN[0].GT  \
8700000  chr5  76875427.0  .   A   C  13335.400      .  408.0  1.0       1/1
8700001  chr5  76875427.0  .   A   C  13335.400      .  408.0  1.0       1/1
8700002  chr5  77063199.0  .   C   A   4440.890      .  149.0  1.0       1/1
8700003  chr5  77077415.0  .  AG  GC    603.555      .   19.0  1.0       1/1
8700004  chr5  77413162.0  .   A   G   2368.830      .  175.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
8700000  ...  SRR8898251 NaN NaN NaN NaN NaN NaN         NaN         NaN
8700001  ...  SRR8898251 NaN NaN NaN NaN NaN NaN         NaN         NaN
8700002  ...  SRR8898251 NaN NaN NaN NaN NaN NaN         NaN         NaN
8700003  ...  SRR8898251 NaN NaN NaN NaN NaN NaN         NaN         NaN
8700004  ...  SRR8898251 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
8700000                                        NaN
8700001                                        NaN
8700002                                        NaN
8700003                                        NaN
8700004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
8800000  chr19  15682425.0  .   C   T  3395.21      .  503.0  0.5       0/1
8800001  chr19  15682425.0  .   C   T  3395.21      .  503.0  0.5       0/1
8800002  chr19  15697074.0  .   A   G  7877.12      .  716.0  0.5       0/1
8800003  chr19  15697074.0  .   A   G  7877.12      .  716.0  0.5       0/1
8800004  chr19  15697074.0  .   A   G  7877.12      .  716.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
8800000  ...  SRR8898252 NaN NaN NaN NaN NaN NaN         NaN         NaN
8800001  ...  SRR8898252 NaN NaN NaN NaN NaN NaN         NaN         NaN
8800002  ...  SRR8898252 NaN NaN NaN NaN NaN NaN         NaN         NaN
8800003  ...  SRR8898252 NaN NaN NaN NaN NaN NaN         NaN         NaN
8800004  ...  SRR8898252 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
8800000                                        NaN
8800001                                        NaN
8800002                                        NaN
8800003                                        NaN
8800004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT    QUAL FILTER     DP   AF GEN[0].GT  \
8900000  chr12  48132078.0  .   A   G  4624.3      .  378.0  0.5       0/1
8900001  chr12  48132078.0  .   A   G  4624.3      .  378.0  0.5       0/1
8900002  chr12  48132078.0  .   A   G  4624.3      .  378.0  0.5       0/1
8900003  chr12  48132078.0  .   A   G  4624.3      .  378.0  0.5       0/1
8900004  chr12  48132078.0  .   A   G  4624.3      .  378.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
8900000  ...  SRR8898253 NaN NaN NaN NaN NaN NaN         NaN         NaN
8900001  ...  SRR8898253 NaN NaN NaN NaN NaN NaN         NaN         NaN
8900002  ...  SRR8898253 NaN NaN NaN NaN NaN NaN         NaN         NaN
8900003  ...  SRR8898253 NaN NaN NaN NaN NaN NaN         NaN         NaN
8900004  ...  SRR8898253 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
8900000                                        NaN
8900001                                        NaN
8900002                                        NaN
8900003                                        NaN
8900004                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT     QUAL FILTER      DP   AF GEN[0].GT  \
9000000  chr8  144851323.0  .   C   T  29581.0      .   911.0  1.0       1/1
9000001  chr8  144851323.0  .   C   T  29581.0      .   911.0  1.0       1/1
9000002  chr8  144851323.0  .   C   T  29581.0      .   911.0  1.0       1/1
9000003  chr8  144889982.0  .   A   G  35399.0      .  1098.0  1.0       1/1
9000004  chr8  144889982.0  .   A   G  35399.0      .  1098.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
9000000  ...  SRR8898253 NaN NaN NaN NaN NaN NaN         NaN         NaN
9000001  ...  SRR8898253 NaN NaN NaN NaN NaN NaN         NaN         NaN
9000002  ...  SRR8898253 NaN NaN NaN NaN NaN NaN         NaN         NaN
9000003  ...  SRR8898253 NaN NaN NaN NaN NaN NaN         NaN         NaN
9000004  ...  SRR8898253 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
9000000                                        NaN
9000001                                        NaN
9000002                                        NaN
9000003                                        NaN
9000004                                        NaN

[5 rows x 30 columns]
        CHROM        POS ID REF ALT          QUAL FILTER    DP   AF GEN[0].GT  \
9100000  chr3  3150518.0  .  AT   A  1.087700e-12      .  90.0  0.5       0/1
9100001  chr3  3150518.0  .  AT   A  1.087700e-12      .  90.0  0.5       0/1
9100002  chr3  3150518.0  .  AT   A  1.087700e-12      .  90.0  0.5       0/1
9100003  chr3  3150518.0  .  AT   A  1.087700e-12      .  90.0  0.5       0/1
9100004  chr3  3150518.0  .  AT   A  1.087700e-12      .  90.0  0.5       0/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
9100000  ...  SRR8898254 NaN NaN NaN NaN NaN NaN         NaN         NaN
9100001  ...  SRR8898254 NaN NaN NaN NaN NaN NaN         NaN         NaN
9100002  ...  SRR8898254 NaN NaN NaN NaN NaN NaN         NaN         NaN
9100003  ...  SRR8898254 NaN NaN NaN NaN NaN NaN         NaN         NaN
9100004  ...  SRR8898254 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
9100000                                        NaN
9100001                                        NaN
9100002                                        NaN
9100003                                        NaN
9100004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,22,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
9200000  chr17  19742625.0  .   A   C  8578.68      .  666.0  0.5       0/1
9200001  chr17  19742625.0  .   A   C  8578.68      .  666.0  0.5       0/1
9200002  chr17  19742625.0  .   A   C  8578.68      .  666.0  0.5       0/1
9200003  chr17  19742625.0  .   A   C  8578.68      .  666.0  0.5       0/1
9200004  chr17  19742625.0  .   A   C  8578.68      .  666.0  0.5       0/1

         ...   Sample_ID  AB   GQ  AO  RO   GT   AD LOF[*].GENE NMD[*].GENE  \
9200000  ...  SRR8898255 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
9200001  ...  SRR8898255 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
9200002  ...  SRR8898255 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
9200003  ...  SRR8898255 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
9200004  ...  SRR8898255 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
9200000                                        NaN
9200001                                        NaN
9200002                                        NaN
9200003                                        NaN
9200004                                        NaN

[5 rows x 30 columns]
         CHROM        POS ID REF ALT     QUAL FILTER     DP   AF  GEN[0].GT  \
9300000  chr11  7651784.0  .   G   A  9727.47      .  286.0  1.0        NaN
9300001  chr11  7665100.0  .  TG  AA  3204.67      .  274.0  0.5        NaN
9300002  chr11  7665100.0  .  TG  AA  3204.67      .  274.0  0.5        NaN
9300003  chr11  7665100.0  .  TG  AA  3204.67      .  274.0  0.5        NaN
9300004  chr11  7665100.0  .  TG  AA  3204.67      .  274.0  0.5        NaN

         ...   Sample_ID        AB GQ     AO     RO  GT AD LOF[*].GENE  \
9300000  ...  SRR8898256  0.000000  .  286.0    0.0   .  .         NaN
9300001  ...  SRR8898256  0.427007  .  117.0  156.0   .  .         NaN
9300002  ...  SRR8898256  0.427007  .  117.0  156.0   .  .         NaN
9300003  ...  SRR8898256  0.427007  .  117.0  156.0   .  .         NaN
9300004  ...  SRR8898256  0.427007  .  117.0  156.0   .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
9300000         NaN                                        NaN
9300001         NaN                                        NaN
9300002         NaN                                        NaN
9300003         NaN                                        NaN
9300004         NaN                                        NaN

[5 rows x 30 columns]
        CHROM         POS ID REF ALT      QUAL FILTER     DP   AF  GEN[0].GT  \
9400000  chr7  21601600.0  .   G   A  12009.00      .  348.0  1.0        NaN
9400001  chr7  21683813.0  .   G   A   8175.35      .  681.0  0.5        NaN
9400002  chr7  21683813.0  .   G   A   8175.35      .  681.0  0.5        NaN
9400003  chr7  21683813.0  .   G   A   8175.35      .  681.0  0.5        NaN
9400004  chr7  21725834.0  .   C   T   7894.03      .  502.0  0.5        NaN

         ...   Sample_ID        AB GQ     AO     RO  GT AD LOF[*].GENE  \
9400000  ...  SRR8898256  0.000000  .  347.0    0.0   .  .         NaN
9400001  ...  SRR8898256  0.434655  .  296.0  385.0   .  .         NaN
9400002  ...  SRR8898256  0.434655  .  296.0  385.0   .  .         NaN
9400003  ...  SRR8898256  0.434655  .  296.0  385.0   .  .         NaN
9400004  ...  SRR8898256  0.547809  .  275.0  227.0   .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
9400000         NaN                                        NaN
9400001         NaN                                        NaN
9400002         NaN                                        NaN
9400003         NaN                                        NaN
9400004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,22,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

        CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
9500000  chr2  178575302.0  .   G   A  8152.23      .  603.0  0.5       NaN
9500001  chr2  178575302.0  .   G   A  8152.23      .  603.0  0.5       NaN
9500002  chr2  178575302.0  .   G   A  8152.23      .  603.0  0.5       NaN
9500003  chr2  178575302.0  .   G   A  8152.23      .  603.0  0.5       NaN
9500004  chr2  178575302.0  .   G   A  8152.23      .  603.0  0.5       NaN

         ...   Sample_ID        AB GQ     AO     RO GT AD LOF[*].GENE  \
9500000  ...  SRR8898257  0.494196  .  298.0  304.0  .  .         NaN
9500001  ...  SRR8898257  0.494196  .  298.0  304.0  .  .         NaN
9500002  ...  SRR8898257  0.494196  .  298.0  304.0  .  .         NaN
9500003  ...  SRR8898257  0.494196  .  298.0  304.0  .  .         NaN
9500004  ...  SRR8898257  0.494196  .  298.0  304.0  .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
9500000         NaN                                        NaN
9500001         NaN                                        NaN
9500002         NaN                                        NaN
9500003         NaN                                        NaN
9500004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,22,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
9600000  chr15  64943580.0  .   A   G  12068.80      .  350.0  1.0       1/1
9600001  chr15  64943580.0  .   A   G  12068.80      .  350.0  1.0       1/1
9600002  chr15  64963027.0  .   T   G   2551.01      .   75.0  1.0       1/1
9600003  chr15  64963027.0  .   T   G   2551.01      .   75.0  1.0       1/1
9600004  chr15  64963027.0  .   T   G   2551.01      .   75.0  1.0       1/1

         ...   Sample_ID  AB   GQ  AO  RO   GT   AD LOF[*].GENE NMD[*].GENE  \
9600000  ...  SRR8898258 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
9600001  ...  SRR8898258 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
9600002  ...  SRR8898258 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
9600003  ...  SRR8898258 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
9600004  ...  SRR8898258 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
9600000                                        NaN
9600001                                        NaN
9600002                                        NaN
9600003                                        NaN
9600004                                        NaN

[5 rows x 30 columns]
        CHROM          POS ID REF ALT     QUAL FILTER     DP   AF  GEN[0].GT  \
9700000  chr1  110167097.0  .  TG  CA  2281.87      .  190.0  0.5        NaN
9700001  chr1  110167097.0  .  TG  CA  2281.87      .  190.0  0.5        NaN
9700002  chr1  110167097.0  .  TG  CA  2281.87      .  190.0  0.5        NaN
9700003  chr1  110195674.0  .   G   A  5530.79      .  386.0  0.5        NaN
9700004  chr1  110339822.0  .   A   G  4494.26      .  140.0  1.0        NaN

         ...   Sample_ID        AB GQ     AO     RO  GT AD LOF[*].GENE  \
9700000  ...  SRR8898259  0.463158  .   88.0  102.0   .  .         NaN
9700001  ...  SRR8898259  0.463158  .   88.0  102.0   .  .         NaN
9700002  ...  SRR8898259  0.463158  .   88.0  102.0   .  .         NaN
9700003  ...  SRR8898259  0.528497  .  204.0  182.0   .  .         NaN
9700004  ...  SRR8898259  0.000000  .  140.0    0.0   .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
9700000         NaN                                        NaN
9700001         NaN                                        NaN
9700002         NaN                                        NaN
9700003         NaN                                        NaN
9700004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (22,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

        CHROM        POS ID REF ALT       QUAL FILTER     DP   AF GEN[0].GT  \
9800000  chr5  1085342.0  .   G   A    330.335      .   27.0  1.0       NaN
9800001  chr5  1216660.0  .   A   G  19090.000      .  579.0  1.0       NaN
9800002  chr5  1216660.0  .   A   G  19090.000      .  579.0  1.0       NaN
9800003  chr5  1216718.0  .   G   A   4503.540      .  362.0  0.5       NaN
9800004  chr5  1216718.0  .   G   A   4503.540      .  362.0  0.5       NaN

         ...   Sample_ID        AB GQ     AO     RO GT AD LOF[*].GENE  \
9800000  ...  SRR8898259  0.000000  .   27.0    0.0  .  .         NaN
9800001  ...  SRR8898259  0.000000  .  579.0    0.0  .  .         NaN
9800002  ...  SRR8898259  0.000000  .  579.0    0.0  .  .         NaN
9800003  ...  SRR8898259  0.475138  .  172.0  190.0  .  .         NaN
9800004  ...  SRR8898259  0.475138  .  172.0  190.0  .  .         NaN

        NMD[*].GENE version https://git-lfs.github.com/spec/v1
9800000         NaN                                        NaN
9800001         NaN                                        NaN
9800002         NaN                                        NaN
9800003         NaN                                        NaN
9800004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM        POS ID REF ALT     QUAL FILTER      DP   AF GEN[0].GT  \
9900000  chr19  1271275.0  .   C   T  43512.4      .  1311.0  1.0       1/1
9900001  chr19  1271275.0  .   C   T  43512.4      .  1311.0  1.0       1/1
9900002  chr19  1271275.0  .   C   T  43512.4      .  1311.0  1.0       1/1
9900003  chr19  1271275.0  .   C   T  43512.4      .  1311.0  1.0       1/1
9900004  chr19  1271275.0  .   C   T  43512.4      .  1311.0  1.0       1/1

         ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
9900000  ...  SRR8898260 NaN NaN NaN NaN NaN NaN         NaN         NaN
9900001  ...  SRR8898260 NaN NaN NaN NaN NaN NaN         NaN         NaN
9900002  ...  SRR8898260 NaN NaN NaN NaN NaN NaN         NaN         NaN
9900003  ...  SRR8898260 NaN NaN NaN NaN NaN NaN         NaN         NaN
9900004  ...  SRR8898260 NaN NaN NaN NaN NaN NaN         NaN         NaN

        version https://git-lfs.github.com/spec/v1
9900000                                        NaN
9900001                                        NaN
9900002                                        NaN
9900003                                        NaN
9900004                                        NaN

[5 rows x 30 columns]
          CHROM        POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
10000000  chr11  5389704.0  .   T   G  19517.8      .  585.0  1.0       1/1
10000001  chr11  5389704.0  .   T   G  19517.8      .  585.0  1.0       1/1
10000002  chr11  5389704.0  .   T   G  19517.8      .  585.0  1.0       1/1
10000003  chr11  5389704.0  .   T   G  19517.8      .  585.0  1.0       1/1
10000004  chr11  5389801.0  .   C   T  14274.0      .  424.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
10000000  ...  SRR8898261 NaN NaN NaN NaN NaN NaN           .            .
10000001  ...  SRR8898261 NaN NaN NaN NaN NaN NaN           .            .
10000002  ...  SRR8898261 NaN NaN NaN NaN NaN NaN           .            .
10000003  ...  SRR8898261 NaN NaN NaN NaN NaN NaN           .            .
10000004  ...  SRR8898261 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
10000000                                         NaN
10000001                                         NaN
10000002                                         NaN
10000003                                         NaN
10000004                                         NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
10100000  chr5  140807737.0  .   C   T  4085.56      .  299.0  0.5       0/1
10100001  chr5  140807737.0  .   C   T  4085.56      .  299.0  0.5       0/1
10100002  chr5  140807737.0  .   C   T  4085.56      .  299.0  0.5       0/1
10100003  chr5  140808798.0  .   T   G  1892.47      .  119.0  0.5       0/1
10100004  chr5  140808798.0  .   T   G  1892.47      .  119.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
10100000  ...  SRR8898261 NaN NaN NaN NaN NaN NaN           .            .
10100001  ...  SRR8898261 NaN NaN NaN NaN NaN NaN           .            .
10100002  ...  SRR8898261 NaN NaN NaN NaN NaN NaN           .            .
10100003  ...  SRR8898261 NaN NaN NaN NaN NaN NaN           .            .
10100004  ...  SRR8898261 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
10100000                                         NaN
10100001                                         NaN
10100002                                         NaN
10100003                                         NaN
10100004                                         NaN

[5 rows x 30 columns]
          CHROM        POS ID REF ALT     QUAL FILTER    DP   AF GEN[0].GT  \
10200000  chr19  1619340.0  .   T   C  637.682      .  51.0  0.5       0/1
10200001  chr19  1619340.0  .   T   C  637.682      .  51.0  0.5       0/1
10200002  chr19  1619340.0  .   T   C  637.682      .  51.0  0.5       0/1
10200003  chr19  1619340.0  .   T   C  637.682      .  51.0  0.5       0/1
10200004  chr19  1619340.0  .   T   C  637.682      .  51.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
10200000  ...  SRR8898262 NaN NaN NaN NaN NaN NaN           .            .
10200001  ...  SRR8898262 NaN NaN NaN NaN NaN NaN           .            .
10200002  ...  SRR8898262 NaN NaN NaN NaN NaN NaN           .            .
10200003  ...  SRR8898262 NaN NaN NaN NaN NaN NaN           .            .
10200004  ...  SRR8898262 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
10200000                                         NaN
10200001                                         NaN
10200002                                         NaN
10200003                                         NaN
10200004                                         NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
10300000  chr11  32104415.0  .   C   T  1055.37      .  190.0  0.5       0/1
10300001  chr11  32104415.0  .   C   T  1055.37      .  190.0  0.5       0/1
10300002  chr11  32104415.0  .   C   T  1055.37      .  190.0  0.5       0/1
10300003  chr11  32104415.0  .   C   T  1055.37      .  190.0  0.5       0/1
10300004  chr11  32104415.0  .   C   T  1055.37      .  190.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
10300000  ...  SRR8898263 NaN NaN NaN NaN NaN NaN           .            .
10300001  ...  SRR8898263 NaN NaN NaN NaN NaN NaN           .            .
10300002  ...  SRR8898263 NaN NaN NaN NaN NaN NaN           .            .
10300003  ...  SRR8898263 NaN NaN NaN NaN NaN NaN           .            .
10300004  ...  SRR8898263 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
10300000                                         NaN
10300001                                         NaN
10300002                                         NaN
10300003                                         NaN
10300004                                         NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT     QUAL FILTER    DP   AF GEN[0].GT  \
10400000  chr5  181241426.0  .   C   A  24.5755      .  16.0  0.5       0/1
10400001  chr5  181241426.0  .   C   A  24.5755      .  16.0  0.5       0/1
10400002  chr5  181241426.0  .   C   A  24.5755      .  16.0  0.5       0/1
10400003  chr5  181241426.0  .   C   A  24.5755      .  16.0  0.5       0/1
10400004  chr5  181241426.0  .   C   A  24.5755      .  16.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
10400000  ...  SRR8898263 NaN NaN NaN NaN NaN NaN           .            .
10400001  ...  SRR8898263 NaN NaN NaN NaN NaN NaN           .            .
10400002  ...  SRR8898263 NaN NaN NaN NaN NaN NaN           .            .
10400003  ...  SRR8898263 NaN NaN NaN NaN NaN NaN           .            .
10400004  ...  SRR8898263 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
10400000                                         NaN
10400001                                         NaN
10400002                                         NaN
10400003                                         NaN
10400004                                         NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
10500000  chr19  21056681.0  .   G   T   3594.36      .  313.0  0.5       0/1
10500001  chr19  21117659.0  .   A   G  11003.00      .  335.0  1.0       1/1
10500002  chr19  21117659.0  .   A   G  11003.00      .  335.0  1.0       1/1
10500003  chr19  21117659.0  .   A   G  11003.00      .  335.0  1.0       1/1
10500004  chr19  21117659.0  .   A   G  11003.00      .  335.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
10500000  ...  SRR8898264 NaN NaN NaN NaN NaN NaN           .            .
10500001  ...  SRR8898264 NaN NaN NaN NaN NaN NaN           .            .
10500002  ...  SRR8898264 NaN NaN NaN NaN NaN NaN           .            .
10500003  ...  SRR8898264 NaN NaN NaN NaN NaN NaN           .            .
10500004  ...  SRR8898264 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
10500000                                         NaN
10500001                                         NaN
10500002                                         NaN
10500003                                         NaN
10500004                                         NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT      QUAL FILTER    DP   AF GEN[0].GT  \
10600000  chr11  72821576.0  .   T   G  1092.480      .  36.0  1.0       1/1
10600001  chr11  72821663.0  .   C   T   887.912      .  29.0  1.0       1/1
10600002  chr11  72821663.0  .   C   T   887.912      .  29.0  1.0       1/1
10600003  chr11  72821663.0  .   C   T   887.912      .  29.0  1.0       1/1
10600004  chr11  72821663.0  .   C   T   887.912      .  29.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
10600000  ...  SRR8898265 NaN NaN NaN NaN NaN NaN           .            .
10600001  ...  SRR8898265 NaN NaN NaN NaN NaN NaN           .            .
10600002  ...  SRR8898265 NaN NaN NaN NaN NaN NaN           .            .
10600003  ...  SRR8898265 NaN NaN NaN NaN NaN NaN           .            .
10600004  ...  SRR8898265 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
10600000                                         NaN
10600001                                         NaN
10600002                                         NaN
10600003                                         NaN
10600004                                         NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT          QUAL FILTER    DP   AF  \
10700000  chr4  142237901.0  .   C   G  1.671460e-09      .  26.0  0.0
10700001  chr4  142237901.0  .   C   G  1.671460e-09      .  26.0  0.0
10700002  chr4  142237901.0  .   C   G  1.671460e-09      .  26.0  0.0
10700003  chr4  142237901.0  .   C   G  1.671460e-09      .  26.0  0.0
10700004  chr4  142237901.0  .   C   G  1.671460e-09      .  26.0  0.0

         GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
10700000       0/0  ...  SRR8898265 NaN NaN NaN NaN NaN NaN           .
10700001       0/0  ...  SRR8898265 NaN NaN NaN NaN NaN NaN           .
10700002       0/0  ...  SRR8898265 NaN NaN NaN NaN NaN NaN           .
10700003       0/0  ...  SRR8898265 NaN NaN NaN NaN NaN NaN           .
10700004       0/0  ...  SRR8898265 NaN NaN NaN NaN NaN NaN           .

          NMD[*].GENE  version https://git-lfs.github.com/spec/v1
10700000            .                                         NaN
10700001            .                                         NaN
10700002            .                                         NaN
10700003            .                                         NaN
10700004            .                                         NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

          CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
10800000  chr17  50550731.0  .   A   G  6094.99      .  371.0  0.5       0/1
10800001  chr17  50550731.0  .   A   G  6094.99      .  371.0  0.5       0/1
10800002  chr17  50550731.0  .   A   G  6094.99      .  371.0  0.5       0/1
10800003  chr17  50550731.0  .   A   G  6094.99      .  371.0  0.5       0/1
10800004  chr17  50550731.0  .   A   G  6094.99      .  371.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
10800000  ...  SRR8898266 NaN NaN NaN NaN NaN NaN           .           .
10800001  ...  SRR8898266 NaN NaN NaN NaN NaN NaN           .           .
10800002  ...  SRR8898266 NaN NaN NaN NaN NaN NaN           .           .
10800003  ...  SRR8898266 NaN NaN NaN NaN NaN NaN           .           .
10800004  ...  SRR8898266 NaN NaN NaN NaN NaN NaN           .           .

         version https://git-lfs.github.com/spec/v1
10800000                                        NaN
10800001                                        NaN
10800002                                        NaN
10800003                                        NaN
10800004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
10900000  chr10  86453835.0  .   A   C   1746.19      .  154.0  0.5       0/1
10900001  chr10  86453835.0  .   A   C   1746.19      .  154.0  0.5       0/1
10900002  chr10  86453835.0  .   A   C   1746.19      .  154.0  0.5       0/1
10900003  chr10  86517700.0  .   C   T  10718.00      .  795.0  0.5       0/1
10900004  chr10  86517700.0  .   C   T  10718.00      .  795.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
10900000  ...  SRR8898267 NaN NaN NaN NaN NaN NaN         NaN         NaN
10900001  ...  SRR8898267 NaN NaN NaN NaN NaN NaN         NaN         NaN
10900002  ...  SRR8898267 NaN NaN NaN NaN NaN NaN         NaN         NaN
10900003  ...  SRR8898267 NaN NaN NaN NaN NaN NaN         NaN         NaN
10900004  ...  SRR8898267 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
10900000                                        NaN
10900001                                        NaN
10900002                                        NaN
10900003                                        NaN
10900004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
11000000  chr6  73823468.0  .   G   T   3739.86      .  250.0  0.5       0/1
11000001  chr6  73823468.0  .   G   T   3739.86      .  250.0  0.5       0/1
11000002  chr6  73823468.0  .   G   T   3739.86      .  250.0  0.5       0/1
11000003  chr6  75087586.0  .   C   T  18662.00      .  566.0  1.0       1/1
11000004  chr6  75087586.0  .   C   T  18662.00      .  566.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
11000000  ...  SRR8898267 NaN NaN NaN NaN NaN NaN         NaN         NaN
11000001  ...  SRR8898267 NaN NaN NaN NaN NaN NaN         NaN         NaN
11000002  ...  SRR8898267 NaN NaN NaN NaN NaN NaN         NaN         NaN
11000003  ...  SRR8898267 NaN NaN NaN NaN NaN NaN         NaN         NaN
11000004  ...  SRR8898267 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
11000000                                        NaN
11000001                                        NaN
11000002                                        NaN
11000003                                        NaN
11000004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
11100000  chr19  45364001.0  .   C   T  1970.91      .  165.0  0.5       0/1
11100001  chr19  45364001.0  .   C   T  1970.91      .  165.0  0.5       0/1
11100002  chr19  45364001.0  .   C   T  1970.91      .  165.0  0.5       0/1
11100003  chr19  45364001.0  .   C   T  1970.91      .  165.0  0.5       0/1
11100004  chr19  45364001.0  .   C   T  1970.91      .  165.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
11100000  ...  SRR8898268 NaN NaN NaN NaN NaN NaN         NaN         NaN
11100001  ...  SRR8898268 NaN NaN NaN NaN NaN NaN         NaN         NaN
11100002  ...  SRR8898268 NaN NaN NaN NaN NaN NaN         NaN         NaN
11100003  ...  SRR8898268 NaN NaN NaN NaN NaN NaN         NaN         NaN
11100004  ...  SRR8898268 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
11100000                                        NaN
11100001                                        NaN
11100002                                        NaN
11100003                                        NaN
11100004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF    ALT      QUAL FILTER     DP   AF  \
11200000  chr12  26631917.0  .   G      A  1980.000      .  139.0  0.5
11200001  chr12  26631917.0  .   G      A  1980.000      .  139.0  0.5
11200002  chr12  26657844.0  .   T      C  1920.110      .  158.0  0.5
11200003  chr12  26658112.0  .   T      C   779.996      .   82.0  0.5
11200004  chr12  26681871.0  .   T  TACTC  5463.440      .  189.0  1.0

         GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
11200000       0/1  ...  SRR8898269 NaN NaN NaN NaN NaN NaN         NaN
11200001       0/1  ...  SRR8898269 NaN NaN NaN NaN NaN NaN         NaN
11200002       0/1  ...  SRR8898269 NaN NaN NaN NaN NaN NaN         NaN
11200003       0/1  ...  SRR8898269 NaN NaN NaN NaN NaN NaN         NaN
11200004       1/1  ...  SRR8898269 NaN NaN NaN NaN NaN NaN         NaN

         NMD[*].GENE version https://git-lfs.github.com/spec/v1
11200000         NaN                                        NaN
11200001         NaN                                        NaN
11200002         NaN                                        NaN
11200003         NaN                                        NaN
11200004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM          POS ID REF ALT     QUAL FILTER    DP   AF GEN[0].GT  \
11300000  chr7  102227604.0  .  CC  GT  61.1925      .  27.0  0.5       0/1
11300001  chr7  102227604.0  .  CC  GT  61.1925      .  27.0  0.5       0/1
11300002  chr7  102227604.0  .  CC  GT  61.1925      .  27.0  0.5       0/1
11300003  chr7  102227604.0  .  CC  GT  61.1925      .  27.0  0.5       0/1
11300004  chr7  102227604.0  .  CC  GT  61.1925      .  27.0  0.5       0/1

          ...   Sample_ID  AB   GQ  AO  RO   GT   AD LOF[*].GENE NMD[*].GENE  \
11300000  ...  SRR8898269 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
11300001  ...  SRR8898269 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
11300002  ...  SRR8898269 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
11300003  ...  SRR8898269 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
11300004  ...  SRR8898269 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
11300000                                        NaN
11300001                                        NaN
11300002                                        NaN
11300003                                        NaN
11300004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,22,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
11400000  chr2  27101856.0  .   G   C  14999.1      .  448.0  1.0       NaN
11400001  chr2  27101856.0  .   G   C  14999.1      .  448.0  1.0       NaN
11400002  chr2  27101856.0  .   G   C  14999.1      .  448.0  1.0       NaN
11400003  chr2  27101856.0  .   G   C  14999.1      .  448.0  1.0       NaN
11400004  chr2  27101883.0  .   G   T  16009.2      .  479.0  1.0       NaN

          ...   Sample_ID   AB GQ     AO   RO GT AD LOF[*].GENE NMD[*].GENE  \
11400000  ...  SRR8898270  0.0  .  448.0  0.0  .  .         NaN         NaN
11400001  ...  SRR8898270  0.0  .  448.0  0.0  .  .         NaN         NaN
11400002  ...  SRR8898270  0.0  .  448.0  0.0  .  .         NaN         NaN
11400003  ...  SRR8898270  0.0  .  448.0  0.0  .  .         NaN         NaN
11400004  ...  SRR8898270  0.0  .  478.0  1.0  .  .         NaN         NaN

         version https://git-lfs.github.com/spec/v1
11400000                                        NaN
11400001                                        NaN
11400002                                        NaN
11400003                                        NaN
11400004                                        NaN

[5 rows x 30 columns]
          CHROM          POS ID REF ALT          QUAL FILTER     DP   AF  \
11500000  chr12  103966001.0  .   C   T  4.224980e-14      .  163.0  0.5
11500001  chr12  103966001.0  .   C   T  4.224980e-14      .  163.0  0.5
11500002  chr12  103966001.0  .   C   T  4.224980e-14      .  163.0  0.5
11500003  chr12  103966001.0  .   C   T  4.224980e-14      .  163.0  0.5
11500004  chr12  103966001.0  .   C   T  4.224980e-14      .  163.0  0.5

         GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
11500000       0/1  ...  SRR8898271 NaN NaN NaN NaN NaN NaN         NaN
11500001       0/1  ...  SRR8898271 NaN NaN NaN NaN NaN NaN         NaN
11500002       0/1  ...  SRR8898271 NaN NaN NaN NaN NaN NaN         NaN
11500003       0/1  ...  SRR8898271 NaN NaN NaN NaN NaN NaN         NaN
11500004       0/1  ...  SRR8898271 NaN NaN NaN NaN NaN NaN         NaN

         NMD[*].GENE version https://git-lfs.github.com/spec/v1
11500000         NaN                                        NaN
11500001         NaN                                        NaN
11500002         NaN                                        NaN
11500003         NaN                                        NaN
11500004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
11600000  chr9  98578019.0  .   A   C  22625.6      .  691.0  1.0       1/1
11600001  chr9  98578019.0  .   A   C  22625.6      .  691.0  1.0       1/1
11600002  chr9  98578034.0  .   T   C   9717.3      .  701.0  0.5       0/1
11600003  chr9  98578034.0  .   T   C   9717.3      .  701.0  0.5       0/1
11600004  chr9  98578034.0  .   T   C   9717.3      .  701.0  0.5       0/1

          ...   Sample_ID  AB   GQ  AO  RO   GT   AD LOF[*].GENE NMD[*].GENE  \
11600000  ...  SRR8898271 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
11600001  ...  SRR8898271 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
11600002  ...  SRR8898271 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
11600003  ...  SRR8898271 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
11600004  ...  SRR8898271 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
11600000                                        NaN
11600001                                        NaN
11600002                                        NaN
11600003                                        NaN
11600004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,22,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM        POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
11700000  chr3  9928474.0  .   C   T  3282.97      .  236.0  0.5       NaN
11700001  chr3  9933125.0  .   G   A  3206.71      .  239.0  0.5       NaN
11700002  chr3  9933125.0  .   G   A  3206.71      .  239.0  0.5       NaN
11700003  chr3  9933125.0  .   G   A  3206.71      .  239.0  0.5       NaN
11700004  chr3  9933125.0  .   G   A  3206.71      .  239.0  0.5       NaN

          ...   Sample_ID        AB GQ     AO     RO GT AD LOF[*].GENE  \
11700000  ...  SRR8898272  0.508475  .  120.0  116.0  .  .         NaN
11700001  ...  SRR8898272  0.518828  .  124.0  115.0  .  .         NaN
11700002  ...  SRR8898272  0.518828  .  124.0  115.0  .  .         NaN
11700003  ...  SRR8898272  0.518828  .  124.0  115.0  .  .         NaN
11700004  ...  SRR8898272  0.518828  .  124.0  115.0  .  .         NaN

         NMD[*].GENE version https://git-lfs.github.com/spec/v1
11700000         NaN                                        NaN
11700001         NaN                                        NaN
11700002         NaN                                        NaN
11700003         NaN                                        NaN
11700004         NaN                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT      QUAL FILTER    DP   AF GEN[0].GT  \
11800000  chr15  34337669.0  .   C   A   199.664      .  12.0  0.5       0/1
11800001  chr15  34337669.0  .   C   A   199.664      .  12.0  0.5       0/1
11800002  chr15  34348017.0  .   C   T  3199.640      .  96.0  1.0       1/1
11800003  chr15  34348017.0  .   C   T  3199.640      .  96.0  1.0       1/1
11800004  chr15  34348017.0  .   C   T  3199.640      .  96.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
11800000  ...  SRR8898273 NaN NaN NaN NaN NaN NaN         NaN         NaN
11800001  ...  SRR8898273 NaN NaN NaN NaN NaN NaN         NaN         NaN
11800002  ...  SRR8898273 NaN NaN NaN NaN NaN NaN         NaN         NaN
11800003  ...  SRR8898273 NaN NaN NaN NaN NaN NaN         NaN         NaN
11800004  ...  SRR8898273 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
11800000                                        NaN
11800001                                        NaN
11800002                                        NaN
11800003                                        NaN
11800004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT          QUAL FILTER    DP   AF  \
11900000  chr7  18668842.0  .   G   A  1.186030e-08      .  25.0  0.0
11900001  chr7  18954247.0  .   C   T  3.594570e+02      .  12.0  1.0
11900002  chr7  18954247.0  .   C   T  3.594570e+02      .  12.0  1.0
11900003  chr7  18954247.0  .   C   T  3.594570e+02      .  12.0  1.0
11900004  chr7  18954247.0  .   C   T  3.594570e+02      .  12.0  1.0

         GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
11900000       0/0  ...  SRR8898273 NaN NaN NaN NaN NaN NaN         NaN
11900001       1/1  ...  SRR8898273 NaN NaN NaN NaN NaN NaN         NaN
11900002       1/1  ...  SRR8898273 NaN NaN NaN NaN NaN NaN         NaN
11900003       1/1  ...  SRR8898273 NaN NaN NaN NaN NaN NaN         NaN
11900004       1/1  ...  SRR8898273 NaN NaN NaN NaN NaN NaN         NaN

         NMD[*].GENE version https://git-lfs.github.com/spec/v1
11900000         NaN                                        NaN
11900001         NaN                                        NaN
11900002         NaN                                        NaN
11900003         NaN                                        NaN
11900004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,22,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

          CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
12000000  chr19  57492978.0  .   G   C  2545.56      .  197.0  0.5       0/1
12000001  chr19  57492978.0  .   G   C  2545.56      .  197.0  0.5       0/1
12000002  chr19  57492978.0  .   G   C  2545.56      .  197.0  0.5       0/1
12000003  chr19  57492978.0  .   G   C  2545.56      .  197.0  0.5       0/1
12000004  chr19  57492978.0  .   G   C  2545.56      .  197.0  0.5       0/1

          ...   Sample_ID  AB   GQ  AO  RO   GT   AD LOF[*].GENE NMD[*].GENE  \
12000000  ...  SRR8898274 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
12000001  ...  SRR8898274 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
12000002  ...  SRR8898274 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
12000003  ...  SRR8898274 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN
12000004  ...  SRR8898274 NaN  NaN NaN NaN  NaN  NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
12000000                                        NaN
12000001                                        NaN
12000002                                        NaN
12000003                                        NaN
12000004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT          QUAL FILTER     DP   AF  \
12100000  chr14  19666486.0  .   C   T  1.042680e-14      .  148.0  0.0
12100001  chr14  19666486.0  .   C   T  1.042680e-14      .  148.0  0.0
12100002  chr14  19666486.0  .   C   T  1.042680e-14      .  148.0  0.0
12100003  chr14  19748139.0  .   T   C  6.777320e+03      .  907.0  0.5
12100004  chr14  19748139.0  .   T   C  6.777320e+03      .  907.0  0.5

          GEN[0].GT  ...   Sample_ID        AB GQ     AO     RO  GT AD  \
12100000        NaN  ...  SRR8898275  0.000000  .   22.0  126.0   .  .
12100001        NaN  ...  SRR8898275  0.000000  .   22.0  126.0   .  .
12100002        NaN  ...  SRR8898275  0.000000  .   22.0  126.0   .  .
12100003        NaN  ...  SRR8898275  0.323043  .  293.0  614.0   .  .
12100004        NaN  ...  SRR8898275  0.323043  .  293.0  614.0   .  .

         LOF[*].GENE NMD[*].GENE version https://git-lfs.github.com/spec/v1
12100000         NaN         NaN                                        NaN
12100001         NaN         NaN                                        NaN
12100002         NaN         NaN                                        NaN
12100003         NaN         NaN                                        NaN
12100004         NaN         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (22,25,26) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
12200000  chr9  137463520.0  .   A   G  7577.44      .  230.0  1.0       NaN
12200001  chr9  137463520.0  .   A   G  7577.44      .  230.0  1.0       NaN
12200002  chr9  137463520.0  .   A   G  7577.44      .  230.0  1.0       NaN
12200003  chr9  137467395.0  .   G   A  3874.17      .  306.0  0.5       NaN
12200004  chr9  137467395.0  .   G   A  3874.17      .  306.0  0.5       NaN

          ...   Sample_ID        AB GQ     AO     RO GT AD LOF[*].GENE  \
12200000  ...  SRR8898275  0.000000  .  230.0    0.0  .  .         NaN
12200001  ...  SRR8898275  0.000000  .  230.0    0.0  .  .         NaN
12200002  ...  SRR8898275  0.000000  .  230.0    0.0  .  .         NaN
12200003  ...  SRR8898275  0.477124  .  146.0  160.0  .  .         NaN
12200004  ...  SRR8898275  0.477124  .  146.0  160.0  .  .         NaN

         NMD[*].GENE version https://git-lfs.github.com/spec/v1
12200000         NaN                                        NaN
12200001         NaN                                        NaN
12200002         NaN                                        NaN
12200003         NaN                                        NaN
12200004         NaN                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
12300000  chr3  52786965.0  .   A   T  2998.54      .  247.0  0.5       0/1
12300001  chr3  52786965.0  .   A   T  2998.54      .  247.0  0.5       0/1
12300002  chr3  52786965.0  .   A   T  2998.54      .  247.0  0.5       0/1
12300003  chr3  52786995.0  .   A   G  3113.66      .  240.0  0.5       0/1
12300004  chr3  52786995.0  .   A   G  3113.66      .  240.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
12300000  ...  SRR8898276 NaN NaN NaN NaN NaN NaN         NaN         NaN
12300001  ...  SRR8898276 NaN NaN NaN NaN NaN NaN         NaN         NaN
12300002  ...  SRR8898276 NaN NaN NaN NaN NaN NaN         NaN         NaN
12300003  ...  SRR8898276 NaN NaN NaN NaN NaN NaN         NaN         NaN
12300004  ...  SRR8898276 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
12300000                                        NaN
12300001                                        NaN
12300002                                        NaN
12300003                                        NaN
12300004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT     QUAL FILTER    DP   AF GEN[0].GT  \
12400000  chr17  42670290.0  .   C   A  1271.01      .  43.0  1.0       1/1
12400001  chr17  42670290.0  .   C   A  1271.01      .  43.0  1.0       1/1
12400002  chr17  42670290.0  .   C   A  1271.01      .  43.0  1.0       1/1
12400003  chr17  42670290.0  .   C   A  1271.01      .  43.0  1.0       1/1
12400004  chr17  42670290.0  .   C   A  1271.01      .  43.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
12400000  ...  SRR8898277 NaN NaN NaN NaN NaN NaN         NaN         NaN
12400001  ...  SRR8898277 NaN NaN NaN NaN NaN NaN         NaN         NaN
12400002  ...  SRR8898277 NaN NaN NaN NaN NaN NaN         NaN         NaN
12400003  ...  SRR8898277 NaN NaN NaN NaN NaN NaN         NaN         NaN
12400004  ...  SRR8898277 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
12400000                                        NaN
12400001                                        NaN
12400002                                        NaN
12400003                                        NaN
12400004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
12500000  chr11  26565847.0  .   T   C  4934.98      .  423.0  0.5       0/1
12500001  chr11  26565847.0  .   T   C  4934.98      .  423.0  0.5       0/1
12500002  chr11  26565847.0  .   T   C  4934.98      .  423.0  0.5       0/1
12500003  chr11  26565847.0  .   T   C  4934.98      .  423.0  0.5       0/1
12500004  chr11  26565847.0  .   T   C  4934.98      .  423.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
12500000  ...  SRR8898278 NaN NaN NaN NaN NaN NaN         NaN         NaN
12500001  ...  SRR8898278 NaN NaN NaN NaN NaN NaN         NaN         NaN
12500002  ...  SRR8898278 NaN NaN NaN NaN NaN NaN         NaN         NaN
12500003  ...  SRR8898278 NaN NaN NaN NaN NaN NaN         NaN         NaN
12500004  ...  SRR8898278 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
12500000                                        NaN
12500001                                        NaN
12500002                                        NaN
12500003                                        NaN
12500004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
12600000  chr7  36616429.0  .   G   C  5076.78      .  390.0  0.5       0/1
12600001  chr7  36690152.0  .   T   C  4835.37      .  146.0  1.0       1/1
12600002  chr7  36690152.0  .   T   C  4835.37      .  146.0  1.0       1/1
12600003  chr7  36690152.0  .   T   C  4835.37      .  146.0  1.0       1/1
12600004  chr7  36690152.0  .   T   C  4835.37      .  146.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
12600000  ...  SRR8898278 NaN NaN NaN NaN NaN NaN         NaN         NaN
12600001  ...  SRR8898278 NaN NaN NaN NaN NaN NaN         NaN         NaN
12600002  ...  SRR8898278 NaN NaN NaN NaN NaN NaN         NaN         NaN
12600003  ...  SRR8898278 NaN NaN NaN NaN NaN NaN         NaN         NaN
12600004  ...  SRR8898278 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
12600000                                        NaN
12600001                                        NaN
12600002                                        NaN
12600003                                        NaN
12600004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
12700000  chr2  132785001.0  .   C   T  6251.01      .  418.0  0.5       0/1
12700001  chr2  132785001.0  .   C   T  6251.01      .  418.0  0.5       0/1
12700002  chr2  132785001.0  .   C   T  6251.01      .  418.0  0.5       0/1
12700003  chr2  132796715.0  .   A   G  5318.90      .  462.0  0.5       0/1
12700004  chr2  132796715.0  .   A   G  5318.90      .  462.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
12700000  ...  SRR8898279 NaN NaN NaN NaN NaN NaN         NaN         NaN
12700001  ...  SRR8898279 NaN NaN NaN NaN NaN NaN         NaN         NaN
12700002  ...  SRR8898279 NaN NaN NaN NaN NaN NaN         NaN         NaN
12700003  ...  SRR8898279 NaN NaN NaN NaN NaN NaN         NaN         NaN
12700004  ...  SRR8898279 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
12700000                                        NaN
12700001                                        NaN
12700002                                        NaN
12700003                                        NaN
12700004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
12800000  chr14  87976368.0  .   C   T  10329.00      .  832.0  0.5       0/1
12800001  chr14  87976368.0  .   C   T  10329.00      .  832.0  0.5       0/1
12800002  chr14  87992401.0  .   C   T   3962.09      .  297.0  0.5       0/1
12800003  chr14  87992401.0  .   C   T   3962.09      .  297.0  0.5       0/1
12800004  chr14  87992401.0  .   C   T   3962.09      .  297.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
12800000  ...  SRR8898280 NaN NaN NaN NaN NaN NaN           .            .
12800001  ...  SRR8898280 NaN NaN NaN NaN NaN NaN           .            .
12800002  ...  SRR8898280 NaN NaN NaN NaN NaN NaN           .            .
12800003  ...  SRR8898280 NaN NaN NaN NaN NaN NaN           .            .
12800004  ...  SRR8898280 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
12800000                                         NaN
12800001                                         NaN
12800002                                         NaN
12800003                                         NaN
12800004                                         NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT  QUAL FILTER     DP   AF GEN[0].GT  \
12900000  chr9  105506391.0  .   C   T   0.0      .  300.0  0.0       0/0
12900001  chr9  105506391.0  .   C   T   0.0      .  300.0  0.0       0/0
12900002  chr9  105506391.0  .   C   T   0.0      .  300.0  0.0       0/0
12900003  chr9  105506391.0  .   C   T   0.0      .  300.0  0.0       0/0
12900004  chr9  105506391.0  .   C   T   0.0      .  300.0  0.0       0/0

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
12900000  ...  SRR8898280 NaN NaN NaN NaN NaN NaN           .            .
12900001  ...  SRR8898280 NaN NaN NaN NaN NaN NaN           .            .
12900002  ...  SRR8898280 NaN NaN NaN NaN NaN NaN           .            .
12900003  ...  SRR8898280 NaN NaN NaN NaN NaN NaN           .            .
12900004  ...  SRR8898280 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
12900000                                         NaN
12900001                                         NaN
12900002                                         NaN
12900003                                         NaN
12900004                                         NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT        QUAL FILTER     DP   AF  \
13000000  chr20  46613630.0  .   G   C  5887.05000      .  511.0  0.5
13000001  chr20  46613630.0  .   G   C  5887.05000      .  511.0  0.5
13000002  chr20  46613630.0  .   G   C  5887.05000      .  511.0  0.5
13000003  chr20  47210440.0  .   C   T     0.02497      .    8.0  0.5
13000004  chr20  47210440.0  .   C   T     0.02497      .    8.0  0.5

         GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
13000000       0/1  ...  SRR8898281 NaN NaN NaN NaN NaN NaN           .
13000001       0/1  ...  SRR8898281 NaN NaN NaN NaN NaN NaN           .
13000002       0/1  ...  SRR8898281 NaN NaN NaN NaN NaN NaN           .
13000003       0/1  ...  SRR8898281 NaN NaN NaN NaN NaN NaN           .
13000004       0/1  ...  SRR8898281 NaN NaN NaN NaN NaN NaN           .

          NMD[*].GENE  version https://git-lfs.github.com/spec/v1
13000000            .                                         NaN
13000001            .                                         NaN
13000002            .                                         NaN
13000003            .                                         NaN
13000004            .                                         NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT          QUAL FILTER     DP   AF  \
13100000  chr15  32968854.0  .   T   G  2.200340e-15      .   44.0  0.0
13100001  chr15  32968854.0  .   T   G  2.200340e-15      .   44.0  0.0
13100002  chr15  32968854.0  .   T   G  2.200340e-15      .   44.0  0.0
13100003  chr15  32969031.0  .   G   A  1.294940e+03      .  103.0  0.5
13100004  chr15  32969031.0  .   G   A  1.294940e+03      .  103.0  0.5

         GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
13100000       0/0  ...  SRR8898282 NaN NaN NaN NaN NaN NaN           .
13100001       0/0  ...  SRR8898282 NaN NaN NaN NaN NaN NaN           .
13100002       0/0  ...  SRR8898282 NaN NaN NaN NaN NaN NaN           .
13100003       0/1  ...  SRR8898282 NaN NaN NaN NaN NaN NaN           .
13100004       0/1  ...  SRR8898282 NaN NaN NaN NaN NaN NaN           .

          NMD[*].GENE  version https://git-lfs.github.com/spec/v1
13100000            .                                         NaN
13100001            .                                         NaN
13100002            .                                         NaN
13100003            .                                         NaN
13100004            .                                         NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM          POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
13200000  chr9  133439376.0  .   G   A  12902.80      .  394.0  1.0       1/1
13200001  chr9  133439376.0  .   G   A  12902.80      .  394.0  1.0       1/1
13200002  chr9  133439376.0  .   G   A  12902.80      .  394.0  1.0       1/1
13200003  chr9  133443421.0  .   T   C   2941.78      .   89.0  1.0       1/1
13200004  chr9  133443421.0  .   T   C   2941.78      .   89.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
13200000  ...  SRR8898282 NaN NaN NaN NaN NaN NaN           .           .
13200001  ...  SRR8898282 NaN NaN NaN NaN NaN NaN           .           .
13200002  ...  SRR8898282 NaN NaN NaN NaN NaN NaN           .           .
13200003  ...  SRR8898282 NaN NaN NaN NaN NaN NaN           .           .
13200004  ...  SRR8898282 NaN NaN NaN NaN NaN NaN           .           .

         version https://git-lfs.github.com/spec/v1
13200000                                        NaN
13200001                                        NaN
13200002                                        NaN
13200003                                        NaN
13200004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID    REF    ALT          QUAL FILTER     DP   AF  \
13300000  chr3  75737298.0  .  CGTAC  TGTAT  1.126010e+02      .  394.0  0.5
13300001  chr3  75737348.0  .     CA     TG  0.000000e+00      .  390.0  0.0
13300002  chr3  75737348.0  .     CA     TG  0.000000e+00      .  390.0  0.0
13300003  chr3  75737348.0  .     CA     TG  0.000000e+00      .  390.0  0.0
13300004  chr3  75737364.0  .     GG     AT  2.621770e-14      .  349.0  0.0

         GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
13300000       0/1  ...  SRR8898283 NaN NaN NaN NaN NaN NaN         NaN
13300001       0/0  ...  SRR8898283 NaN NaN NaN NaN NaN NaN         NaN
13300002       0/0  ...  SRR8898283 NaN NaN NaN NaN NaN NaN         NaN
13300003       0/0  ...  SRR8898283 NaN NaN NaN NaN NaN NaN         NaN
13300004       0/0  ...  SRR8898283 NaN NaN NaN NaN NaN NaN         NaN

         NMD[*].GENE version https://git-lfs.github.com/spec/v1
13300000         NaN                                        NaN
13300001         NaN                                        NaN
13300002         NaN                                        NaN
13300003         NaN                                        NaN
13300004         NaN                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT          QUAL FILTER     DP   AF  \
13400000  chr17  42979628.0  .   C   A  5.758600e+03      .  502.0  0.5
13400001  chr17  42979628.0  .   C   A  5.758600e+03      .  502.0  0.5
13400002  chr17  42979628.0  .   C   A  5.758600e+03      .  502.0  0.5
13400003  chr17  42980833.0  .   A   T  1.185090e-14      .   38.0  0.0
13400004  chr17  42980833.0  .   A   T  1.185090e-14      .   38.0  0.0

         GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
13400000       0/1  ...  SRR8898284 NaN NaN NaN NaN NaN NaN         NaN
13400001       0/1  ...  SRR8898284 NaN NaN NaN NaN NaN NaN         NaN
13400002       0/1  ...  SRR8898284 NaN NaN NaN NaN NaN NaN         NaN
13400003       0/0  ...  SRR8898284 NaN NaN NaN NaN NaN NaN         NaN
13400004       0/0  ...  SRR8898284 NaN NaN NaN NaN NaN NaN         NaN

         NMD[*].GENE version https://git-lfs.github.com/spec/v1
13400000         NaN                                        NaN
13400001         NaN                                        NaN
13400002         NaN                                        NaN
13400003         NaN                                        NaN
13400004         NaN                                        NaN

[5 rows x 30 columns]
          CHROM       POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
13500000  chr11  406043.0  .   G   A  1721.73      .  152.0  0.5       0/1
13500001  chr11  406043.0  .   G   A  1721.73      .  152.0  0.5       0/1
13500002  chr11  406043.0  .   G   A  1721.73      .  152.0  0.5       0/1
13500003  chr11  406043.0  .   G   A  1721.73      .  152.0  0.5       0/1
13500004  chr11  406043.0  .   G   A  1721.73      .  152.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
13500000  ...  SRR8898285 NaN NaN NaN NaN NaN NaN         NaN         NaN
13500001  ...  SRR8898285 NaN NaN NaN NaN NaN NaN         NaN         NaN
13500002  ...  SRR8898285 NaN NaN NaN NaN NaN NaN         NaN         NaN
13500003  ...  SRR8898285 NaN NaN NaN NaN NaN NaN         NaN         NaN
13500004  ...  SRR8898285 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
13500000                                        NaN
13500001                                        NaN
13500002                                        NaN
13500003                                        NaN
13500004                                        NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
13600000  chr6  130869698.0  .   G   A  4634.93      .  422.0  0.5       0/1
13600001  chr6  130869698.0  .   G   A  4634.93      .  422.0  0.5       0/1
13600002  chr6  130869698.0  .   G   A  4634.93      .  422.0  0.5       0/1
13600003  chr6  130869698.0  .   G   A  4634.93      .  422.0  0.5       0/1
13600004  chr6  130869698.0  .   G   A  4634.93      .  422.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
13600000  ...  SRR8898285 NaN NaN NaN NaN NaN NaN         NaN         NaN
13600001  ...  SRR8898285 NaN NaN NaN NaN NaN NaN         NaN         NaN
13600002  ...  SRR8898285 NaN NaN NaN NaN NaN NaN         NaN         NaN
13600003  ...  SRR8898285 NaN NaN NaN NaN NaN NaN         NaN         NaN
13600004  ...  SRR8898285 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
13600000                                        NaN
13600001                                        NaN
13600002                                        NaN
13600003                                        NaN
13600004                                        NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT  QUAL FILTER    DP   AF GEN[0].GT  ...  \
13700000  chr2  74490019.0  .   T   C   0.0      .  74.0  0.0       0/0  ...
13700001  chr2  74490019.0  .   T   C   0.0      .  74.0  0.0       0/0  ...
13700002  chr2  74490019.0  .   T   C   0.0      .  74.0  0.0       0/0  ...
13700003  chr2  74490019.0  .   T   C   0.0      .  74.0  0.0       0/0  ...
13700004  chr2  74490019.0  .   T   C   0.0      .  74.0  0.0       0/0  ...

           Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
13700000  SRR8898286 NaN NaN NaN NaN NaN NaN         NaN         NaN
13700001  SRR8898286 NaN NaN NaN NaN NaN NaN         NaN         NaN
13700002  SRR8898286 NaN NaN NaN NaN NaN NaN         NaN         NaN
13700003  SRR8898286 NaN NaN NaN NaN NaN NaN         NaN         NaN
13700004  SRR8898286 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
13700000                                        NaN
13700001                                        NaN
13700002                                        NaN
13700003                                        NaN
13700004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF  ALT      QUAL FILTER    DP   AF GEN[0].GT  \
13800000  chr13  77698132.0  .   T  TGG  256.5930      .  10.0  1.0       1/1
13800001  chr13  77901178.0  .   T    C   76.5744      .  12.0  0.5       0/1
13800002  chr13  77901178.0  .   T    C   76.5744      .  12.0  0.5       0/1
13800003  chr13  77901178.0  .   T    C   76.5744      .  12.0  0.5       0/1
13800004  chr13  77903539.0  .   A    G  690.6120      .  22.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
13800000  ...  SRR8898287 NaN NaN NaN NaN NaN NaN         NaN         NaN
13800001  ...  SRR8898287 NaN NaN NaN NaN NaN NaN         NaN         NaN
13800002  ...  SRR8898287 NaN NaN NaN NaN NaN NaN         NaN         NaN
13800003  ...  SRR8898287 NaN NaN NaN NaN NaN NaN         NaN         NaN
13800004  ...  SRR8898287 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
13800000                                        NaN
13800001                                        NaN
13800002                                        NaN
13800003                                        NaN
13800004                                        NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT          QUAL FILTER    DP   AF  \
13900000  chr7  137015608.0  .   T   C  1.629370e-11      .  22.0  0.0
13900001  chr7  137251278.0  .   C   T  1.207090e-12      .  32.0  0.0
13900002  chr7  137251278.0  .   C   T  1.207090e-12      .  32.0  0.0
13900003  chr7  137407999.0  .  CA   C  5.684130e+02      .  44.0  0.5
13900004  chr7  137407999.0  .  CA   C  5.684130e+02      .  44.0  0.5

         GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
13900000       0/0  ...  SRR8898287 NaN NaN NaN NaN NaN NaN         NaN
13900001       0/0  ...  SRR8898287 NaN NaN NaN NaN NaN NaN         NaN
13900002       0/0  ...  SRR8898287 NaN NaN NaN NaN NaN NaN         NaN
13900003       0/1  ...  SRR8898287 NaN NaN NaN NaN NaN NaN         NaN
13900004       0/1  ...  SRR8898287 NaN NaN NaN NaN NaN NaN         NaN

         NMD[*].GENE version https://git-lfs.github.com/spec/v1
13900000         NaN                                        NaN
13900001         NaN                                        NaN
13900002         NaN                                        NaN
13900003         NaN                                        NaN
13900004         NaN                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19,27,28,29) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

          CHROM        POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
14000000  chr20  3233935.0  .   C   T  1323.33      .  114.0  0.5       0/1
14000001  chr20  3233935.0  .   C   T  1323.33      .  114.0  0.5       0/1
14000002  chr20  3237988.0  .   G   C  3984.95      .  283.0  0.5       0/1
14000003  chr20  3237988.0  .   G   C  3984.95      .  283.0  0.5       0/1
14000004  chr20  3237988.0  .   G   C  3984.95      .  283.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
14000000  ...  SRR8898288 NaN NaN NaN NaN NaN NaN         NaN         NaN
14000001  ...  SRR8898288 NaN NaN NaN NaN NaN NaN         NaN         NaN
14000002  ...  SRR8898288 NaN NaN NaN NaN NaN NaN         NaN         NaN
14000003  ...  SRR8898288 NaN NaN NaN NaN NaN NaN         NaN         NaN
14000004  ...  SRR8898288 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
14000000                                        NaN
14000001                                        NaN
14000002                                        NaN
14000003                                        NaN
14000004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT     QUAL FILTER    DP   AF GEN[0].GT  \
14100000  chr15  40808947.0  .   C   T  445.851      .  59.0  0.5       0/1
14100001  chr15  40808947.0  .   C   T  445.851      .  59.0  0.5       0/1
14100002  chr15  40808947.0  .   C   T  445.851      .  59.0  0.5       0/1
14100003  chr15  40808947.0  .   C   T  445.851      .  59.0  0.5       0/1
14100004  chr15  40808947.0  .   C   T  445.851      .  59.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
14100000  ...  SRR8898290 NaN NaN NaN NaN NaN NaN           .            .
14100001  ...  SRR8898290 NaN NaN NaN NaN NaN NaN           .            .
14100002  ...  SRR8898290 NaN NaN NaN NaN NaN NaN           .            .
14100003  ...  SRR8898290 NaN NaN NaN NaN NaN NaN           .            .
14100004  ...  SRR8898290 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
14100000                                         NaN
14100001                                         NaN
14100002                                         NaN
14100003                                         NaN
14100004                                         NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM         POS ID REF ALT      QUAL FILTER    DP   AF GEN[0].GT  \
14200000  chr9  76175271.0  .   G   C   70.1539      .  97.0  0.5       0/1
14200001  chr9  76175271.0  .   G   C   70.1539      .  97.0  0.5       0/1
14200002  chr9  76175271.0  .   G   C   70.1539      .  97.0  0.5       0/1
14200003  chr9  76175271.0  .   G   C   70.1539      .  97.0  0.5       0/1
14200004  chr9  76175276.0  .   C   G  113.0480      .  84.0  0.5       0/1

          ...   Sample_ID  AB   GQ  AO  RO   GT   AD LOF[*].GENE NMD[*].GENE  \
14200000  ...  SRR8898290 NaN  NaN NaN NaN  NaN  NaN           .           .
14200001  ...  SRR8898290 NaN  NaN NaN NaN  NaN  NaN           .           .
14200002  ...  SRR8898290 NaN  NaN NaN NaN  NaN  NaN           .           .
14200003  ...  SRR8898290 NaN  NaN NaN NaN  NaN  NaN           .           .
14200004  ...  SRR8898290 NaN  NaN NaN NaN  NaN  NaN           .           .

         version https://git-lfs.github.com/spec/v1
14200000                                        NaN
14200001                                        NaN
14200002                                        NaN
14200003                                        NaN
14200004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (9,10,11,15,18,19,22,25,26,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

          CHROM         POS ID REF ALT          QUAL FILTER     DP   AF  \
14300000  chr21  46431882.0  .   G   A  4.693720e+03      .  336.0  0.5
14300001  chr21  46431882.0  .   G   A  4.693720e+03      .  336.0  0.5
14300002  chr21  46432198.0  .   A   G  3.268210e-14      .   36.0  0.0
14300003  chr21  46432198.0  .   A   G  3.268210e-14      .   36.0  0.0
14300004  chr21  46435963.0  .   A   G  5.621300e+03      .  427.0  0.5

         GEN[0].GT  ...   Sample_ID        AB GQ     AO     RO GT AD  \
14300000       NaN  ...  SRR8898291  0.520833  .  175.0  161.0  .  .
14300001       NaN  ...  SRR8898291  0.520833  .  175.0  161.0  .  .
14300002       NaN  ...  SRR8898291  0.000000  .    2.0   34.0  .  .
14300003       NaN  ...  SRR8898291  0.000000  .    2.0   34.0  .  .
14300004       NaN  ...  SRR8898291  0.487119  .  208.0  219.0  .  .

         LOF[*].GENE NMD[*].GENE version https://git-lfs.github.com/spec/v1
14300000         NaN         NaN                                        NaN
14300001         NaN         NaN                                        NaN
14300002         NaN         NaN                                        NaN
14300003         NaN         NaN                                        NaN
14300004         NaN         NaN                                        NaN

[5 rows x 30 columns]
          CHROM       POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
14400000  chr16  625087.0  .  AC   A  1536.490      .  128.0  0.5       0/1
14400001  chr16  631280.0  .   G   T   442.849      .   65.0  0.5       0/1
14400002  chr16  631280.0  .   G   T   442.849      .   65.0  0.5       0/1
14400003  chr16  651656.0  .   C   T  2813.100      .  203.0  0.5       0/1
14400004  chr16  651656.0  .   C   T  2813.100      .  203.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
14400000  ...  SRR8898292 NaN NaN NaN NaN NaN NaN      RAB40C            .
14400001  ...  SRR8898292 NaN NaN NaN NaN NaN NaN           .            .
14400002  ...  SRR8898292 NaN NaN NaN NaN NaN NaN           .            .
14400003  ...  SRR8898292 NaN NaN NaN NaN NaN NaN           .            .
14400004  ...  SRR8898292 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
14400000                                         NaN
14400001                                         NaN
14400002                                         NaN
14400003                                         NaN
14400004                                         NaN

[5 rows x 30 columns]
         CHROM         POS ID REF ALT     QUAL FILTER   DP   AF GEN[0].GT  \
14500000  chr1  26306290.0  .   C   T  77.4407      .  9.0  0.5       0/1
14500001  chr1  26306290.0  .   C   T  77.4407      .  9.0  0.5       0/1
14500002  chr1  26306290.0  .   C   T  77.4407      .  9.0  0.5       0/1
14500003  chr1  26306290.0  .   C   T  77.4407      .  9.0  0.5       0/1
14500004  chr1  26306290.0  .   C   T  77.4407      .  9.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
14500000  ...  SRR8898293 NaN NaN NaN NaN NaN NaN           .            .
14500001  ...  SRR8898293 NaN NaN NaN NaN NaN NaN           .            .
14500002  ...  SRR8898293 NaN NaN NaN NaN NaN NaN           .            .
14500003  ...  SRR8898293 NaN NaN NaN NaN NaN NaN           .            .
14500004  ...  SRR8898293 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
14500000                                         NaN
14500001                                         NaN
14500002                                         NaN
14500003                                         NaN
14500004                                         NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

          CHROM         POS ID REF ALT     QUAL FILTER    DP   AF GEN[0].GT  \
14600000  chr20  37207423.0  .   G   A  1210.62      .  86.0  0.5       0/1
14600001  chr20  37236651.0  .   C   T  3292.10      .  95.0  1.0       1/1
14600002  chr20  37236651.0  .   C   T  3292.10      .  95.0  1.0       1/1
14600003  chr20  37236651.0  .   C   T  3292.10      .  95.0  1.0       1/1
14600004  chr20  37236651.0  .   C   T  3292.10      .  95.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
14600000  ...  SRR8898293 NaN NaN NaN NaN NaN NaN           .           .
14600001  ...  SRR8898293 NaN NaN NaN NaN NaN NaN           .           .
14600002  ...  SRR8898293 NaN NaN NaN NaN NaN NaN           .           .
14600003  ...  SRR8898293 NaN NaN NaN NaN NaN NaN           .           .
14600004  ...  SRR8898293 NaN NaN NaN NaN NaN NaN           .           .

         version https://git-lfs.github.com/spec/v1
14600000                                        NaN
14600001                                        NaN
14600002                                        NaN
14600003                                        NaN
14600004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
14700000  chr14  74946205.0  .   A   G   3162.14      .  103.0  1.0       1/1
14700001  chr14  74946205.0  .   A   G   3162.14      .  103.0  1.0       1/1
14700002  chr14  74946205.0  .   A   G   3162.14      .  103.0  1.0       1/1
14700003  chr14  75017109.0  .   T   C  20171.90      .  608.0  1.0       1/1
14700004  chr14  75017109.0  .   T   C  20171.90      .  608.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
14700000  ...  SRR8898294 NaN NaN NaN NaN NaN NaN         NaN         NaN
14700001  ...  SRR8898294 NaN NaN NaN NaN NaN NaN         NaN         NaN
14700002  ...  SRR8898294 NaN NaN NaN NaN NaN NaN         NaN         NaN
14700003  ...  SRR8898294 NaN NaN NaN NaN NaN NaN         NaN         NaN
14700004  ...  SRR8898294 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
14700000                                        NaN
14700001                                        NaN
14700002                                        NaN
14700003                                        NaN
14700004                                        NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT          QUAL FILTER     DP   AF  \
14800000  chrX  103309655.0  .   A   G  1.172520e+04      .  386.0  1.0
14800001  chrX  103309655.0  .   A   G  1.172520e+04      .  386.0  1.0
14800002  chrX  103309655.0  .   A   G  1.172520e+04      .  386.0  1.0
14800003  chrX  103501927.0  .   T   C  3.477610e-14      .   36.0  0.0
14800004  chrX  103501927.0  .   T   C  3.477610e-14      .   36.0  0.0

         GEN[0].GT  ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  \
14800000       1/1  ...  SRR8898294 NaN NaN NaN NaN NaN NaN         NaN
14800001       1/1  ...  SRR8898294 NaN NaN NaN NaN NaN NaN         NaN
14800002       1/1  ...  SRR8898294 NaN NaN NaN NaN NaN NaN         NaN
14800003       0/0  ...  SRR8898294 NaN NaN NaN NaN NaN NaN         NaN
14800004       0/0  ...  SRR8898294 NaN NaN NaN NaN NaN NaN         NaN

         NMD[*].GENE version https://git-lfs.github.com/spec/v1
14800000         NaN                                        NaN
14800001         NaN                                        NaN
14800002         NaN                                        NaN
14800003         NaN                                        NaN
14800004         NaN                                        NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT      QUAL FILTER     DP   AF GEN[0].GT  \
14900000  chr3  167333981.0  .   T   C   532.313      .   19.0  1.0       1/1
14900001  chr3  167333981.0  .   T   C   532.313      .   19.0  1.0       1/1
14900002  chr3  167350468.0  .   T   A  4275.550      .  132.0  1.0       1/1
14900003  chr3  167350468.0  .   T   A  4275.550      .  132.0  1.0       1/1
14900004  chr3  167350468.0  .   T   A  4275.550      .  132.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
14900000  ...  SRR8898295 NaN NaN NaN NaN NaN NaN         NaN         NaN
14900001  ...  SRR8898295 NaN NaN NaN NaN NaN NaN         NaN         NaN
14900002  ...  SRR8898295 NaN NaN NaN NaN NaN NaN         NaN         NaN
14900003  ...  SRR8898295 NaN NaN NaN NaN NaN NaN         NaN         NaN
14900004  ...  SRR8898295 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
14900000                                        NaN
14900001                                        NaN
14900002                                        NaN
14900003                                        NaN
14900004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

          CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
15000000  chr17  78223510.0  .   G   A  3289.54      .  100.0  1.0       1/1
15000001  chr17  78223510.0  .   G   A  3289.54      .  100.0  1.0       1/1
15000002  chr17  78223510.0  .   G   A  3289.54      .  100.0  1.0       1/1
15000003  chr17  78233902.0  .   C   T  2616.77      .  221.0  0.5       0/1
15000004  chr17  78233902.0  .   C   T  2616.77      .  221.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
15000000  ...  SRR8898296 NaN NaN NaN NaN NaN NaN         NaN         NaN
15000001  ...  SRR8898296 NaN NaN NaN NaN NaN NaN         NaN         NaN
15000002  ...  SRR8898296 NaN NaN NaN NaN NaN NaN         NaN         NaN
15000003  ...  SRR8898296 NaN NaN NaN NaN NaN NaN         NaN         NaN
15000004  ...  SRR8898296 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
15000000                                        NaN
15000001                                        NaN
15000002                                        NaN
15000003                                        NaN
15000004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT    QUAL FILTER   DP   AF GEN[0].GT  \
15100000  chr11  17076507.0  .   G   A  1.6832      .  9.0  0.5       0/1
15100001  chr11  17076507.0  .   G   A  1.6832      .  9.0  0.5       0/1
15100002  chr11  17076507.0  .   G   A  1.6832      .  9.0  0.5       0/1
15100003  chr11  17076507.0  .   G   A  1.6832      .  9.0  0.5       0/1
15100004  chr11  17076507.0  .   G   A  1.6832      .  9.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
15100000  ...  SRR8898297 NaN NaN NaN NaN NaN NaN           .            .
15100001  ...  SRR8898297 NaN NaN NaN NaN NaN NaN           .            .
15100002  ...  SRR8898297 NaN NaN NaN NaN NaN NaN           .            .
15100003  ...  SRR8898297 NaN NaN NaN NaN NaN NaN           .            .
15100004  ...  SRR8898297 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
15100000                                         NaN
15100001                                         NaN
15100002                                         NaN
15100003                                         NaN
15100004                                         NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
15200000  chr6  10775367.0  .   G   A  5752.05      .  393.0  0.5       0/1
15200001  chr6  10775367.0  .   G   A  5752.05      .  393.0  0.5       0/1
15200002  chr6  10775367.0  .   G   A  5752.05      .  393.0  0.5       0/1
15200003  chr6  10775367.0  .   G   A  5752.05      .  393.0  0.5       0/1
15200004  chr6  10775367.0  .   G   A  5752.05      .  393.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
15200000  ...  SRR8898297 NaN NaN NaN NaN NaN NaN           .           .
15200001  ...  SRR8898297 NaN NaN NaN NaN NaN NaN           .           .
15200002  ...  SRR8898297 NaN NaN NaN NaN NaN NaN           .           .
15200003  ...  SRR8898297 NaN NaN NaN NaN NaN NaN           .           .
15200004  ...  SRR8898297 NaN NaN NaN NaN NaN NaN           .           .

         version https://git-lfs.github.com/spec/v1
15200000                                        NaN
15200001                                        NaN
15200002                                        NaN
15200003                                        NaN
15200004                                        NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (18,19,27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

          CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
15300000  chr19  42935542.0  .   G   A  21135.6      .  640.0  1.0       1/1
15300001  chr19  43015210.0  .   C   T  14782.9      .  452.0  1.0       1/1
15300002  chr19  43015210.0  .   C   T  14782.9      .  452.0  1.0       1/1
15300003  chr19  43015210.0  .   C   T  14782.9      .  452.0  1.0       1/1
15300004  chr19  43015210.0  .   C   T  14782.9      .  452.0  1.0       1/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
15300000  ...  SRR8898298 NaN NaN NaN NaN NaN NaN         NaN         NaN
15300001  ...  SRR8898298 NaN NaN NaN NaN NaN NaN         NaN         NaN
15300002  ...  SRR8898298 NaN NaN NaN NaN NaN NaN         NaN         NaN
15300003  ...  SRR8898298 NaN NaN NaN NaN NaN NaN         NaN         NaN
15300004  ...  SRR8898298 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
15300000                                        NaN
15300001                                        NaN
15300002                                        NaN
15300003                                        NaN
15300004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
15400000  chr12  42384944.0  .   C   T  3928.06      .  354.0  0.5       0/1
15400001  chr12  42384944.0  .   C   T  3928.06      .  354.0  0.5       0/1
15400002  chr12  42384944.0  .   C   T  3928.06      .  354.0  0.5       0/1
15400003  chr12  42384944.0  .   C   T  3928.06      .  354.0  0.5       0/1
15400004  chr12  42384944.0  .   C   T  3928.06      .  354.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE  NMD[*].GENE  \
15400000  ...  SRR8898299 NaN NaN NaN NaN NaN NaN           .            .
15400001  ...  SRR8898299 NaN NaN NaN NaN NaN NaN           .            .
15400002  ...  SRR8898299 NaN NaN NaN NaN NaN NaN           .            .
15400003  ...  SRR8898299 NaN NaN NaN NaN NaN NaN           .            .
15400004  ...  SRR8898299 NaN NaN NaN NaN NaN NaN           .            .

          version https://git-lfs.github.com/spec/v1
15400000                                         NaN
15400001                                         NaN
15400002                                         NaN
15400003                                         NaN
15400004                                         NaN

[5 rows x 30 columns]

/tmp/ipython-input-2276229899.py:1: DtypeWarning: Columns (27,28) have mixed types. Specify dtype option on import or set low_memory=False.
  for chunk in pd.read_csv('Merged_AD_WES_variants.tsv', sep='\t', chunksize=100000):

         CHROM          POS ID REF ALT  QUAL FILTER      DP   AF GEN[0].GT  \
15500000  chr7  100958241.0  .   A   C   0.0      .  1119.0  0.0       0/0
15500001  chr7  100958241.0  .   A   C   0.0      .  1119.0  0.0       0/0
15500002  chr7  100958244.0  .   C   A   0.0      .  1122.0  0.0       0/0
15500003  chr7  100958244.0  .   C   A   0.0      .  1122.0  0.0       0/0
15500004  chr7  100958244.0  .   C   A   0.0      .  1122.0  0.0       0/0

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
15500000  ...  SRR8898299 NaN NaN NaN NaN NaN NaN           .           .
15500001  ...  SRR8898299 NaN NaN NaN NaN NaN NaN           .           .
15500002  ...  SRR8898299 NaN NaN NaN NaN NaN NaN           .           .
15500003  ...  SRR8898299 NaN NaN NaN NaN NaN NaN           .           .
15500004  ...  SRR8898299 NaN NaN NaN NaN NaN NaN           .           .

         version https://git-lfs.github.com/spec/v1
15500000                                        NaN
15500001                                        NaN
15500002                                        NaN
15500003                                        NaN
15500004                                        NaN

[5 rows x 30 columns]
         CHROM          POS ID REF ALT      QUAL FILTER    DP   AF GEN[0].GT  \
15600000  chr2  202829152.0  .   T   G  0.004351      .  15.0  0.5       0/1
15600001  chr2  202829152.0  .   T   G  0.004351      .  15.0  0.5       0/1
15600002  chr2  202829152.0  .   T   G  0.004351      .  15.0  0.5       0/1
15600003  chr2  202829152.0  .   T   G  0.004351      .  15.0  0.5       0/1
15600004  chr2  202829152.0  .   T   G  0.004351      .  15.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
15600000  ...  SRR8898300 NaN NaN NaN NaN NaN NaN         NaN         NaN
15600001  ...  SRR8898300 NaN NaN NaN NaN NaN NaN         NaN         NaN
15600002  ...  SRR8898300 NaN NaN NaN NaN NaN NaN         NaN         NaN
15600003  ...  SRR8898300 NaN NaN NaN NaN NaN NaN         NaN         NaN
15600004  ...  SRR8898300 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
15600000                                        NaN
15600001                                        NaN
15600002                                        NaN
15600003                                        NaN
15600004                                        NaN

[5 rows x 30 columns]
          CHROM         POS ID REF ALT     QUAL FILTER     DP   AF GEN[0].GT  \
15700000  chr15  74207764.0  .   G   A  4595.23      .  279.0  0.5       0/1
15700001  chr15  74207764.0  .   G   A  4595.23      .  279.0  0.5       0/1
15700002  chr15  74207764.0  .   G   A  4595.23      .  279.0  0.5       0/1
15700003  chr15  74207764.0  .   G   A  4595.23      .  279.0  0.5       0/1
15700004  chr15  74207764.0  .   G   A  4595.23      .  279.0  0.5       0/1

          ...   Sample_ID  AB  GQ  AO  RO  GT  AD LOF[*].GENE NMD[*].GENE  \
15700000  ...  SRR8898301 NaN NaN NaN NaN NaN NaN         NaN         NaN
15700001  ...  SRR8898301 NaN NaN NaN NaN NaN NaN         NaN         NaN
15700002  ...  SRR8898301 NaN NaN NaN NaN NaN NaN         NaN         NaN
15700003  ...  SRR8898301 NaN NaN NaN NaN NaN NaN         NaN         NaN
15700004  ...  SRR8898301 NaN NaN NaN NaN NaN NaN         NaN         NaN

         version https://git-lfs.github.com/spec/v1
15700000                                        NaN
15700001                                        NaN
15700002                                        NaN
15700003                                        NaN
15700004                                        NaN

[5 rows x 30 columns]

#PART B — MERGING VCF FILES

###Locate all VCF files

In [ ]:
import glob

# vcf variant files from WES analysis
vcf_dir = "/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered"
#sorted() ensures consistent ordering across runs
vcf_files = sorted(glob.glob(f"{vcf_dir}/*.vcf"))

#Print the total number of vcf files and preview the first few file
print("Total VCF files found:", len(vcf_files))
vcf_files[:5]

Total VCF files found: 111

['/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898191_DP10_impact.vcf',
 '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898192_DP10_impact.vcf',
 '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898193_DP10_impact.vcf',
 '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898194_DP10_impact.vcf',
 '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898195_DP10_impact.vcf']

###INSTALL TOOLS ---bcftools and tabix

In [ ]:
# Install bcftools and tabix (which includes bgzip)
!apt-get update
!apt-get install -y bcftools tabix

Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:7 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [85.0 kB]
Get:8 https://cli.github.com/packages stable/main amd64 Packages [356 B]
Get:9 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:11 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,894 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [62.6 kB]
Get:13 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease [24.6 kB]
Get:14 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,297 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [70.9 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,040 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,725 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,683 kB]
Get:19 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,396 kB]
Get:20 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.8 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,609 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,678 kB]
Get:23 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 Packages [75.3 kB]
Fetched 37.1 MB in 4s (9,507 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libhts3 libhtscodecs2
Suggested packages:
  python3-numpy python3-matplotlib texlive-latex-recommended
The following NEW packages will be installed:
  bcftools libhts3 libhtscodecs2 tabix
0 upgraded, 4 newly installed, 0 to remove and 55 not upgraded.
Need to get 1,491 kB of archives.
After this operation, 4,626 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libhtscodecs2 amd64 1.1.1-3 [53.2 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libhts3 amd64 1.13+ds-2build1 [390 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 bcftools amd64 1.13-1 [697 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tabix amd64 1.13+ds-2build1 [351 kB]
Fetched 1,491 kB in 1s (1,105 kB/s)
Selecting previously unselected package libhtscodecs2:amd64.
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../libhtscodecs2_1.1.1-3_amd64.deb ...
Unpacking libhtscodecs2:amd64 (1.1.1-3) ...
Selecting previously unselected package libhts3:amd64.
Preparing to unpack .../libhts3_1.13+ds-2build1_amd64.deb ...
Unpacking libhts3:amd64 (1.13+ds-2build1) ...
Selecting previously unselected package bcftools.
Preparing to unpack .../bcftools_1.13-1_amd64.deb ...
Unpacking bcftools (1.13-1) ...
Selecting previously unselected package tabix.
Preparing to unpack .../tabix_1.13+ds-2build1_amd64.deb ...
Unpacking tabix (1.13+ds-2build1) ...
Setting up libhtscodecs2:amd64 (1.1.1-3) ...
Setting up libhts3:amd64 (1.13+ds-2build1) ...
Setting up bcftools (1.13-1) ...
Setting up tabix (1.13+ds-2build1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.11) ...
/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

In [ ]:
# Verify installation

!bcftools --version
!tabix --version
!bgzip --version

bcftools 1.13
Using htslib 1.13+ds
Copyright (C) 2021 Genome Research Ltd.
License Expat: The MIT/Expat license
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
tabix (htslib) 1.13+ds
Copyright (C) 2021 Genome Research Ltd.
bgzip (htslib) 1.13+ds
Copyright (C) 2021 Genome Research Ltd.

###bgzip-compress ALL VCF files

This is mandatory — bcftools merge cannot safely merge many uncompressed VCFs.
*   **os**         → file and path handling
*   **subprocess** → run shell commands (bgzip, bcftools)
*   **bgzip** is required for indexing and merging with bcftools

In [ ]:
# Import required libraries

import os
import subprocess
# Initialize an empty list to store bgzip-compressed VCF file paths

gz_vcf_files = []

# Compress each VCF file using bgzip
# bgzip is required for indexing and merging with bcftools
for vcf in vcf_files:
    gz_vcf = vcf + ".gz"
    subprocess.run(f"bgzip -c {vcf} > {gz_vcf}", shell=True)
    gz_vcf_files.append(gz_vcf)

print("Compression completed")

Compression completed

In [ ]:
#Print list of compressed VCF files
print(gz_vcf_files)

['/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898191_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898192_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898193_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898194_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898195_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898196_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898197_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898198_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898199_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898200_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898201_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898202_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898203_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898204_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898205_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898206_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898207_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898208_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898209_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898210_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898211_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898212_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898213_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898214_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898215_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898216_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898217_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898218_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898219_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898220_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898221_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898222_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898223_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898224_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898225_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898226_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898227_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898228_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898229_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898230_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898231_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898232_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898233_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898234_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898235_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898236_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898237_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898238_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898239_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898240_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898241_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898242_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898243_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898244_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898245_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898246_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898247_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898248_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898249_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898250_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898251_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898252_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898253_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898254_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898255_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898256_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898257_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898258_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898259_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898260_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898261_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898262_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898263_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898264_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898265_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898266_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898267_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898268_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898269_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898270_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898271_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898272_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898273_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898274_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898275_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898276_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898277_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898278_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898279_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898280_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898281_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898282_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898283_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898284_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898285_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898286_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898287_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898288_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898289_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898290_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898291_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898292_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898293_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898294_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898295_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898296_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898297_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898298_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898299_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898300_DP10_impact.vcf.gz', '/content/Whole-Exome-sequencing-Variant-Analysis/data/vcf_filtered/SRR8898301_DP10_impact.vcf.gz']

###Index ALL compressed VCFs
Also mandatory to avoid chromosome order errors.
Creates .tbi index files (required internally)

In [ ]:
# Index each compressed VCF using bcftools

for gz_vcf in gz_vcf_files:
    subprocess.run(f"bcftools index -f {gz_vcf}", shell=True)

print("Indexing completed")

Indexing completed

###Create a VCF list file
his file will be used as input for bcftools merge

In [ ]:
# Create a text file listing all compressed VCFs

vcf_list_file = "vcf_list.txt"

with open(vcf_list_file, "w") as f:
    for vcf in gz_vcf_files:
        f.write(vcf + "\n")

print("VCF list file created")

VCF list file created

###Merge VCFs using --force-samples
Because: 1.   All samples are named 'unknown' 2. Each VCF = one individual 3. Filenames preserve identity
* --force-samples → allows identical sample names
* -m none         → do not merge multiallelic sites
* -l              → input list of VCF files
* -Ov             → output in uncompressed VCF format

In [ ]:
# Merge all indexed VCF files into a single VCF

merged_vcf = "AD_Cohort_111_merged.vcf"

!bcftools merge \
    --force-samples \
    -m none \
    -l vcf_list.txt \
    -Ov \
    -o {merged_vcf}

In [ ]:
# View header
!bcftools view -h AD_Cohort_111_merged.vcf | head -n 40

# Basic stats
!bcftools stats AD_Cohort_111_merged.vcf | head -n 20

##fileformat=VCFv4.2
##FILTER=<ID=PASS,Description="All filters passed">
##fileDate=20260126
##source=freeBayes v1.3.10
##reference=/cvmfs/data.galaxyproject.org/byhand/hg38/sam_index/hg38.fa
##contig=<ID=chr1,length=248956422>
##contig=<ID=chr1_KI270706v1_random,length=175055>
##contig=<ID=chr1_KI270707v1_random,length=32032>
##contig=<ID=chr1_KI270708v1_random,length=127682>
##contig=<ID=chr1_KI270709v1_random,length=66860>
##contig=<ID=chr1_KI270710v1_random,length=40176>
##contig=<ID=chr1_KI270711v1_random,length=42210>
##contig=<ID=chr1_KI270712v1_random,length=176043>
##contig=<ID=chr1_KI270713v1_random,length=40745>
##contig=<ID=chr1_KI270714v1_random,length=41717>
##contig=<ID=chr1_GL383518v1_alt,length=182439>
##contig=<ID=chr1_GL383519v1_alt,length=110268>
##contig=<ID=chr1_GL383520v2_alt,length=366580>
##contig=<ID=chr1_KI270759v1_alt,length=425601>
##contig=<ID=chr1_KI270760v1_alt,length=109528>
##contig=<ID=chr1_KI270761v1_alt,length=165834>
##contig=<ID=chr1_KI270762v1_alt,length=354444>
##contig=<ID=chr1_KI270763v1_alt,length=911658>
##contig=<ID=chr1_KI270764v1_alt,length=50258>
##contig=<ID=chr1_KI270765v1_alt,length=185285>
##contig=<ID=chr1_KI270766v1_alt,length=256271>
##contig=<ID=chr1_KI270892v1_alt,length=162212>
##contig=<ID=chr2,length=242193529>
##contig=<ID=chr2_KI270715v1_random,length=161471>
##contig=<ID=chr2_KI270716v1_random,length=153799>
##contig=<ID=chr2_GL383521v1_alt,length=143390>
##contig=<ID=chr2_GL383522v1_alt,length=123821>
##contig=<ID=chr2_GL582966v2_alt,length=96131>
##contig=<ID=chr2_KI270767v1_alt,length=161578>
##contig=<ID=chr2_KI270768v1_alt,length=110099>
##contig=<ID=chr2_KI270769v1_alt,length=120616>
##contig=<ID=chr2_KI270770v1_alt,length=136240>
##contig=<ID=chr2_KI270771v1_alt,length=110395>
##contig=<ID=chr2_KI270772v1_alt,length=133041>
##contig=<ID=chr2_KI270773v1_alt,length=70887>
# This file was produced by bcftools stats (1.13+htslib-1.13+ds) and can be plotted using plot-vcfstats.
# The command line was:	bcftools stats  AD_Cohort_111_merged.vcf
#
# Definition of sets:
# ID	[2]id	[3]tab-separated file names
ID	0	AD_Cohort_111_merged.vcf
# SN, Summary numbers:
#   number of records   .. number of data rows in the VCF
#   number of no-ALTs   .. reference-only sites, ALT is either "." or identical to REF
#   number of SNPs      .. number of rows with a SNP
#   number of MNPs      .. number of rows with a MNP, such as CC>TT
#   number of indels    .. number of rows with an indel
#   number of others    .. number of rows with other type, for example a symbolic allele or
#                          a complex substitution, such as ACT>TCGA
#   number of multiallelic sites     .. number of rows with multiple alternate alleles
#   number of multiallelic SNP sites .. number of rows with multiple alternate alleles, all SNPs
#
#   Note that rows containing multiple types will be counted multiple times, in each
#   counter. For example, a row with a SNP and an indel increments both the SNP and
#   the indel counter.

###Download of AD_Cohort_111_merged.vcf

In [ ]:
from google.colab import files

files.download('AD_Cohort_111_merged.vcf')